//! The generated TypeScript modules. Keys are sorted and the layout is fixed, so two builds of the
//! same inputs write the same bytes. The layout is the one the repository's formatter (Biome)
//! produces: tabs, single quotes, every object literal expanded, and shader sources as template
//! literals.
//!
//! The main module holds the types, every shader that the manifest does not load by device, and
//! the loader of the device modules. Each of those shaders is an export of its own, so a bundle
//! keeps only the shaders that its code imports: the engine's download holds none of the test
//! shaders. The shaders that load by device go into one device module for each target and each
//! value of the permutation bits that a device fixes. Each is a file of its own that the loader
//! imports on demand, so a page downloads only the builds its device draws with. The builds with
//! the bits of a feature that loads on demand (`permutation::ON_DEMAND`) go into modules of their
//! own beside those, which hold only those builds, so a page that never draws the feature
//! downloads none of them.

use std::collections::BTreeMap;

use null3d_gpu::drawlist::permutation;

use crate::glsl::DEPTH_MAPPING_UNIFORM;
use crate::{GlslStage, Output, Target, VariantOutput};

/// The formatter's line width, and the width it counts for one tab.
const LINE_WIDTH: usize = 100;
const TAB_WIDTH: usize = 2;

/// The file name of the main module, without its extension.
pub(crate) const MAIN_MODULE: &str = "shaders";

/// The start of each device module's file name.
pub(crate) const DEVICE_MODULE_PREFIX: &str = "shaders-";

/// The comment at the top of every module.
const HEADER: &str = r"// Generated by `bun run shaders` (cargo run -p null3d-shaders --bin shader-build) from
// crates/null3d-shaders/shaders.toml and the WGSL files beside it. Do not edit this file: git
// ignores it, and the next build replaces it.
";

/// The types of the records.
const TYPES: &str = r"
/** The WGSL bind group and binding of a resource. */
export interface ShaderBinding {
	readonly group: number;
	readonly binding: number;
}

/** A uniform block of one GLSL shader, and the WGSL uniform buffer it stands for. */
export interface GlslUniformBlock extends ShaderBinding {
	/** The block name, for `getUniformBlockIndex`. */
	readonly name: string;
}

/**
 * A texture uniform of one GLSL shader. GLSL ES 3.00 joins a texture and its sampler in one
 * uniform, so the record names the WGSL texture and the WGSL sampler.
 */
export interface GlslTexture extends ShaderBinding {
	/** The uniform name, for `getUniformLocation`. */
	readonly name: string;
	/** The sampler the shader samples the texture with, or null when it only loads texels. */
	readonly sampler: ShaderBinding | null;
}

/**
 * One GLSL ES 3.00 shader. GLSL ES 3.00 has no binding numbers, so the WebGL2 backend binds each
 * uniform block and texture by the name it has in this shader.
 */
export interface GlslStage {
	readonly source: string;
	readonly uniformBlocks: readonly GlslUniformBlock[];
	readonly textures: readonly GlslTexture[];
}

/**
 * The shaders of one render pipeline, to link into one WebGL2 program. The vertex shader maps
 * depth through the uniform that `DEPTH_MAPPING_UNIFORM` names, and keeps GL's row order: the
 * canvas shows the image the right way up, a pixel read returns the bottom row first, and front
 * faces wind counter-clockwise, as on WebGPU. A vertex shader that reads the instance or draw
 * index also declares the uniform `naga_vs_first_instance`, which the backend leaves unset
 * because WebGL2 draws have no first instance.
 */
export interface GlslProgram {
	readonly vertex: GlslStage;
	readonly fragment: GlslStage;
}

/** The WGSL entry points of one render pipeline. */
export interface WgslPipeline {
	readonly vertex: string;
	readonly fragment: string;
}

/** One WGSL module for WebGPU, and the entry points of its render pipelines. */
export interface WgslShader<Pipeline extends string = string> {
	readonly source: string;
	readonly pipelines: Readonly<Record<Pipeline, WgslPipeline>>;
}

/** One variant of a shader, with its output for each backend it targets. */
export interface ShaderVariant<Pipeline extends string = string> {
	/**
	 * The permutation bits that the variant was built with, as a render pipeline's permutation
	 * word holds them: 0 for a variant without permutation bits.
	 */
	readonly permutation: number;
	/** WGSL for WebGPU, or null when the variant does not target WebGPU. */
	readonly wgsl: WgslShader<Pipeline> | null;
	/** GLSL programs for WebGL2 by pipeline, or null when the variant does not target WebGL2. */
	readonly glsl: Readonly<Record<Pipeline, GlslProgram>> | null;
}

/** A shader's variants by name. */
export type ShaderVariants<Pipeline extends string = string> = Readonly<
	Record<string, ShaderVariant<Pipeline>>
>;
";

/// The type of the loader tables, before them.
const LOADER_TYPE: &str = r"
/** Loaders of device modules, by the permutation bits that a device fixes. */
type DeviceModules = Readonly<Record<number, () => Promise<{ SHADERS: DeviceShaders }>>>;
";

/// The loaders of the device modules, after the loader tables. Each target has a table and a
/// function of its own, so a bundle that loads one target's shaders holds none of the other's.
const LOADERS: &str = r"
function loadDeviceModule(modules: DeviceModules, target: string, bits: number) {
	const load = modules[bits];
	if (!load) {
		const message = `no shader module holds the ${target} builds with permutation bits ${bits}`;
		return Promise.reject(new Error(message));
	}
	return load().then((module) => module.SHADERS);
}

/**
 * Loads the WGSL builds of the shaders that load by device, with the permutation bits `bits`,
 * which holds only bits that a device fixes. Each value of those bits is a module of its own, so a
 * page downloads one.
 */
export function loadWgslShaders(bits: number): Promise<DeviceShaders> {
	return loadDeviceModule(WGSL_MODULES, 'WGSL', bits);
}

/**
 * Loads the GLSL builds of the shaders that load by device, with the permutation bits `bits`,
 * which holds only bits that a device fixes and bits of features that load on demand. Each value
 * of those bits is a module of its own, so a page downloads one, and one more for each such
 * feature that it draws. A feature's module holds only the builds with its bits.
 */
export function loadGlslShaders(bits: number): Promise<DeviceShaders> {
	return loadDeviceModule(GLSL_MODULES, 'GLSL', bits);
}

/**
 * Every shader variant, by shader name and variant name: those of this module and those of every
 * device module, for the tests that check them all.
 */
export async function everyShader(): Promise<Record<string, ShaderVariants>> {
	const every: Record<string, ShaderVariants> = { ...SHADERS };
	for (const load of [...Object.values(WGSL_MODULES), ...Object.values(GLSL_MODULES)]) {
		for (const [name, variants] of Object.entries((await load()).SHADERS)) {
			every[name] = { ...every[name], ...variants };
		}
	}
	return every;
}
";

/// A device module: the builds of the shaders that load by device for one target, with one value
/// of the permutation bits that a device fixes.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct DeviceModule {
    target: Target,
    bits: u32,
}

impl DeviceModule {
    /// The module that holds a build of a shader that loads by device. Such a build has one target.
    fn of(variant: &VariantOutput) -> Self {
        let target = if variant.wgsl.is_some() {
            Target::Wgsl
        } else {
            Target::Glsl
        };
        Self {
            target,
            bits: variant.permutation & (permutation::DEVICE | permutation::ON_DEMAND),
        }
    }

    /// The names of the module's bits, in bit order.
    fn bit_names(self) -> impl Iterator<Item = &'static str> {
        permutation::NAMES
            .into_iter()
            .filter(move |&(_, value)| self.bits & value != 0)
            .map(|(name, _)| name)
    }

    /// The file name without its extension: the prefix, the target, then each bit's name in
    /// lowercase with hyphens, such as `shaders-glsl-draw-index`.
    fn stem(self) -> String {
        let mut stem = format!("{DEVICE_MODULE_PREFIX}{}", self.target.name());
        for name in self.bit_names() {
            stem.push('-');
            stem.push_str(&name.to_ascii_lowercase().replace('_', "-"));
        }
        stem
    }
}

/// Builds by shader name, then by variant name.
type Builds<'a> = BTreeMap<&'a str, BTreeMap<&'a str, &'a VariantOutput>>;

/// The builds of the shaders that load by device, by device module. A target has a module for
/// each combination of the device's bits that any of its shaders varies in. Each module holds, of
/// each shader, the builds that a device with the module's bits asks for: those with the module's
/// bits that the shader varies in, so a shader that varies in none is in every module of its
/// target. Each module lists every shader that loads by device, with or without builds in it.
fn device_builds(output: &Output) -> BTreeMap<DeviceModule, Builds<'_>> {
    let shaders = || {
        output
            .by_device
            .iter()
            .filter_map(|shader| Some((shader.as_str(), output.shaders.get(shader)?)))
    };
    let mut varies: BTreeMap<(&str, Target), u32> = BTreeMap::new();
    let mut targets: BTreeMap<Target, u32> = BTreeMap::new();
    for (shader, variants) in shaders() {
        for variant in variants.values() {
            let of = DeviceModule::of(variant);
            *varies.entry((shader, of.target)).or_default() |= of.bits;
            *targets.entry(of.target).or_default() |= of.bits;
        }
    }
    let mut modules = BTreeMap::new();
    for (&target, &all) in &targets {
        let mut bits = all;
        loop {
            let module = DeviceModule { target, bits };
            let mut builds = Builds::new();
            for (shader, variants) in shaders() {
                let asked = bits & varies.get(&(shader, target)).copied().unwrap_or(0);
                let wanted = DeviceModule {
                    target,
                    bits: asked,
                };
                // A module of a feature that loads on demand holds only that feature's builds.
                let on_demand = permutation::ON_DEMAND;
                if (bits ^ asked) & on_demand != 0 {
                    builds.insert(shader, BTreeMap::new());
                    continue;
                }
                builds.insert(
                    shader,
                    variants
                        .iter()
                        .filter(|(_, variant)| DeviceModule::of(variant) == wanted)
                        .map(|(name, variant)| (name.as_str(), variant))
                        .collect(),
                );
            }
            modules.insert(module, builds);
            if bits == 0 {
                break;
            }
            bits = (bits - 1) & all;
        }
    }
    modules
}

/// Renders every module, by file name without its extension: the main module and each device
/// module.
pub(crate) fn modules(output: &Output) -> BTreeMap<String, String> {
    let devices = device_builds(output);
    let mut modules = BTreeMap::from([(MAIN_MODULE.to_owned(), main_module(output, &devices))]);
    for (module, builds) in &devices {
        modules.insert(module.stem(), device_module(*module, builds));
    }
    modules
}

/// The main module: the types, one export per shader that does not load by device, `SHADERS`,
/// which gathers them by name, and the loaders of the device modules.
fn main_module(output: &Output, devices: &BTreeMap<DeviceModule, Builds<'_>>) -> String {
    let mut ts = Writer::default();
    ts.out.push_str(HEADER);
    ts.out.push_str(TYPES);
    ts.line("");
    ts.line("/**");
    ts.line(
        " * The shaders that load by device, each as its variants by name. A device module holds the",
    );
    ts.line(
        " * builds of one target with one value of the permutation bits that a device fixes, and a",
    );
    ts.line(" * shader without builds there has no variants in it.");
    ts.line(" */");
    ts.open("export interface DeviceShaders {");
    for shader in &output.by_device {
        let pipelines = output.pipelines.get(shader).map_or(&[][..], Vec::as_slice);
        ts.line(&format!(
            "readonly {shader}: ShaderVariants<{}>;",
            pipeline_union(pipelines)
        ));
    }
    ts.close("}");
    ts.line("");
    ts.line("/**");
    ts.line(
        " * The uniform through which each GLSL vertex shader maps WebGPU's clip depth: the shader",
    );
    ts.line(" * writes `z * mapping.x + w * mapping.y` as its clip depth, where `mapping` is this vec2.");
    ts.line(" * The WebGL2 backend sets it once per program, for the depth mode it draws with.");
    ts.line(" */");
    ts.line(&format!(
        "export const DEPTH_MAPPING_UNIFORM = {};",
        quote(DEPTH_MAPPING_UNIFORM)
    ));
    let own: Vec<(&String, &BTreeMap<String, VariantOutput>)> = output
        .shaders
        .iter()
        .filter(|(shader, _)| !output.by_device.contains(*shader))
        .collect();
    for &(shader, variants) in &own {
        let pipelines = output.pipelines.get(shader).map_or(&[][..], Vec::as_slice);
        ts.line("");
        ts.line(&format!(
            "/** The variants of the `{shader}` shader, by variant name. */"
        ));
        ts.open(&format!("export const {}: {{", export_name(shader)));
        for variant in variants.keys() {
            ts.variant_type(variant, pipelines);
        }
        ts.depth -= 1;
        ts.open("} = {");
        for (name, variant) in variants {
            ts.open(&format!("{name}: {{"));
            ts.variant(variant);
            ts.close("},");
        }
        ts.close("};");
    }
    ts.line("");
    ts.line("/** The variants of the shaders above, by shader name and variant name. */");
    if own.is_empty() {
        ts.line("export const SHADERS = {} as const;");
    } else {
        ts.open("export const SHADERS = {");
        for &(shader, _) in &own {
            ts.line(&format!("{shader}: {},", export_name(shader)));
        }
        ts.close("} as const;");
    }
    ts.out.push_str(LOADER_TYPE);
    for target in [Target::Wgsl, Target::Glsl] {
        let name = target.name().to_ascii_uppercase();
        let modules: Vec<DeviceModule> = devices
            .keys()
            .copied()
            .filter(|module| module.target == target)
            .collect();
        ts.line("");
        ts.line(&format!(
            "/** The {name} device modules' loaders, by the permutation bits that a device fixes. */"
        ));
        if modules.is_empty() {
            ts.line(&format!("const {name}_MODULES: DeviceModules = {{}};"));
            continue;
        }
        ts.open(&format!("const {name}_MODULES: DeviceModules = {{"));
        for module in modules {
            ts.line(&format!(
                "{}: () => import('./{}'),",
                module.bits,
                module.stem()
            ));
        }
        ts.close("};");
    }
    ts.out.push_str(LOADERS);
    ts.out
}

/// A device module: `SHADERS`, the builds of every shader that loads by device for the module's
/// target and bits.
fn device_module(module: DeviceModule, builds: &Builds<'_>) -> String {
    let mut ts = Writer::default();
    ts.out.push_str(HEADER);
    ts.line("");
    ts.line(&format!(
        "import type {{ DeviceShaders }} from './{MAIN_MODULE}';"
    ));
    ts.line("");
    let bits: Vec<&str> = module.bit_names().collect();
    let with = if bits.is_empty() {
        "without the bits that a device fixes".to_owned()
    } else {
        format!("with {}", bits.join(" and "))
    };
    ts.line(&format!(
        "/** The {} builds of the shaders that load by device, {with}. */",
        module.target.name().to_ascii_uppercase()
    ));
    ts.open("export const SHADERS: DeviceShaders = {");
    for (shader, variants) in builds {
        if variants.is_empty() {
            ts.line(&format!("{shader}: {{}},"));
            continue;
        }
        ts.open(&format!("{shader}: {{"));
        for (name, variant) in variants {
            ts.open(&format!("{name}: {{"));
            ts.variant(variant);
            ts.close("},");
        }
        ts.close("},");
    }
    ts.close("};");
    ts.out
}

/// The union of a shader's pipeline names as a TypeScript type: `never` for none.
fn pipeline_union(pipelines: &[String]) -> String {
    if pipelines.is_empty() {
        return "never".to_owned();
    }
    let names: Vec<String> = pipelines.iter().map(|p| quote(p)).collect();
    names.join(" | ")
}

/// The name of a shader's own export: its name in capitals, then `_SHADER`.
fn export_name(shader: &str) -> String {
    format!("{}_SHADER", shader.to_ascii_uppercase())
}

#[derive(Default)]
struct Writer {
    out: String,
    depth: usize,
}

impl Writer {
    fn line(&mut self, text: &str) {
        for _ in 0..self.depth {
            self.out.push('\t');
        }
        self.out.push_str(text);
        self.out.push('\n');
    }

    fn open(&mut self, text: &str) {
        self.line(text);
        self.depth += 1;
    }

    fn close(&mut self, text: &str) {
        self.depth -= 1;
        self.line(text);
    }

    /// The width the formatter measures for `text` on a line at the current depth.
    fn width(&self, text: &str) -> usize {
        self.depth * TAB_WIDTH + text.chars().count()
    }

    /// A shader source as a template literal. It starts on the key's line and ends with the
    /// closing backtick at the start of a line.
    fn template(&mut self, key: &str, source: &str) {
        for _ in 0..self.depth {
            self.out.push('\t');
        }
        self.out.push_str(key);
        self.out.push_str(": `");
        let mut chars = source.chars().peekable();
        while let Some(c) = chars.next() {
            match c {
                '\\' => self.out.push_str("\\\\"),
                '`' => self.out.push_str("\\`"),
                '$' if chars.peek() == Some(&'{') => self.out.push_str("\\$"),
                _ => self.out.push(c),
            }
        }
        self.out.push_str("`,\n");
    }

    /// The type of one variant, broken over lines the way the formatter breaks a long one.
    fn variant_type(&mut self, variant: &str, pipelines: &[String]) {
        let union = pipeline_union(pipelines);
        let one_line = format!("readonly {variant}: ShaderVariant<{union}>;");
        if self.width(&one_line) <= LINE_WIDTH {
            self.line(&one_line);
            return;
        }
        self.open(&format!("readonly {variant}: ShaderVariant<"));
        if pipelines.len() < 2 || self.width(&union) <= LINE_WIDTH {
            self.line(&union);
        } else {
            for name in pipelines {
                self.line(&format!("| {}", quote(name)));
            }
        }
        self.close(">;");
    }

    fn variant(&mut self, variant: &VariantOutput) {
        self.line(&format!("permutation: {},", variant.permutation));
        match &variant.wgsl {
            None => self.line("wgsl: null,"),
            Some(wgsl) => {
                self.open("wgsl: {");
                self.template("source", &wgsl.source);
                if wgsl.pipelines.is_empty() {
                    self.line("pipelines: {},");
                } else {
                    self.open("pipelines: {");
                    for (name, pipeline) in &wgsl.pipelines {
                        self.open(&format!("{name}: {{"));
                        self.line(&format!("vertex: {},", quote(&pipeline.vertex)));
                        self.line(&format!("fragment: {},", quote(&pipeline.fragment)));
                        self.close("},");
                    }
                    self.close("},");
                }
                self.close("},");
            }
        }
        match &variant.glsl {
            None => self.line("glsl: null,"),
            Some(programs) if programs.is_empty() => self.line("glsl: {},"),
            Some(programs) => {
                self.open("glsl: {");
                for (name, program) in programs {
                    self.open(&format!("{name}: {{"));
                    self.stage("vertex", &program.vertex);
                    self.stage("fragment", &program.fragment);
                    self.close("},");
                }
                self.close("},");
            }
        }
    }

    fn stage(&mut self, key: &str, stage: &GlslStage) {
        self.open(&format!("{key}: {{"));
        self.template("source", &stage.source);
        if stage.uniform_blocks.is_empty() {
            self.line("uniformBlocks: [],");
        } else {
            self.open("uniformBlocks: [");
            for block in &stage.uniform_blocks {
                self.open("{");
                self.line(&format!("name: {},", quote(&block.name)));
                self.binding(block.binding);
                self.close("},");
            }
            self.close("],");
        }
        if stage.textures.is_empty() {
            self.line("textures: [],");
        } else {
            self.open("textures: [");
            for texture in &stage.textures {
                self.open("{");
                self.line(&format!("name: {},", quote(&texture.name)));
                self.binding(texture.binding);
                match texture.sampler {
                    None => self.line("sampler: null,"),
                    Some(sampler) => {
                        self.open("sampler: {");
                        self.binding(sampler);
                        self.close("},");
                    }
                }
                self.close("},");
            }
            self.close("],");
        }
        self.close("},");
    }

    fn binding(&mut self, binding: crate::Binding) {
        self.line(&format!("group: {},", binding.group));
        self.line(&format!("binding: {},", binding.binding));
    }
}

/// A single-quoted string literal.
fn quote(text: &str) -> String {
    format!("'{}'", text.replace('\\', "\\\\").replace('\'', "\\'"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::WgslOutput;

    fn build(target: Target, permutation: u32) -> VariantOutput {
        let wgsl = WgslOutput {
            source: String::new(),
            pipelines: BTreeMap::new(),
        };
        VariantOutput {
            permutation,
            wgsl: (target == Target::Wgsl).then_some(wgsl),
            glsl: (target == Target::Glsl).then(BTreeMap::new),
        }
    }

    /// Two shaders that load by device, as the engine's would with tone mapping in the shader: a
    /// template that varies in both of the device's bits on WebGL2 and in tone mapping on WebGPU,
    /// and a WebGPU compute shader without bits.
    fn output() -> Output {
        use permutation::{DRAW_INDEX, TONE_MAP};
        let mut output = Output::default();
        let mut lit = BTreeMap::new();
        lit.insert("webgpu".to_owned(), build(Target::Wgsl, 0));
        lit.insert("webgpu_tone_map".to_owned(), build(Target::Wgsl, TONE_MAP));
        for (name, bits) in [
            ("webgl2", 0),
            ("webgl2_draw_index", DRAW_INDEX),
            ("webgl2_tone_map", TONE_MAP),
            ("webgl2_draw_index_tone_map", DRAW_INDEX | TONE_MAP),
        ] {
            lit.insert(name.to_owned(), build(Target::Glsl, bits));
        }
        let cull = BTreeMap::from([("webgpu".to_owned(), build(Target::Wgsl, 0))]);
        output.shaders.insert("lit".to_owned(), lit);
        output.shaders.insert("cull".to_owned(), cull);
        output.by_device = ["cull".to_owned(), "lit".to_owned()].into();
        output
    }

    fn names<'a>(builds: &Builds<'a>, shader: &str) -> Vec<&'a str> {
        builds[shader].keys().copied().collect()
    }

    #[test]
    fn each_target_has_a_module_for_each_combination_of_the_bits_its_shaders_vary_in() {
        let output = output();
        let modules = device_builds(&output);
        let stems: Vec<String> = modules.keys().map(|module| module.stem()).collect();
        assert_eq!(
            stems,
            [
                "shaders-wgsl",
                "shaders-wgsl-tone-map",
                "shaders-glsl",
                "shaders-glsl-draw-index",
                "shaders-glsl-tone-map",
                "shaders-glsl-draw-index-tone-map",
            ]
        );
        let module = |target, bits| &modules[&DeviceModule { target, bits }];
        let tone_map = permutation::TONE_MAP;
        let both = permutation::DRAW_INDEX | tone_map;
        assert_eq!(names(module(Target::Wgsl, 0), "lit"), ["webgpu"]);
        assert_eq!(
            names(module(Target::Wgsl, tone_map), "lit"),
            ["webgpu_tone_map"]
        );
        assert_eq!(
            names(module(Target::Glsl, both), "lit"),
            ["webgl2_draw_index_tone_map"]
        );
        for bits in [0, tone_map] {
            assert_eq!(names(module(Target::Wgsl, bits), "cull"), ["webgpu"]);
        }
        assert!(names(module(Target::Glsl, both), "cull").is_empty());
    }

    #[test]
    fn the_main_module_loads_each_device_module_and_holds_none_of_their_shaders() {
        let modules = modules(&output());
        assert_eq!(modules.len(), 7);
        let main = &modules[MAIN_MODULE];
        assert!(main.contains("\treadonly cull: ShaderVariants<never>;\n"));
        assert!(main.contains("\t3: () => import('./shaders-glsl-draw-index-tone-map'),\n"));
        let wgsl = "const WGSL_MODULES: DeviceModules = {\n\t0: () => import('./shaders-wgsl'),\n\t2: () => import('./shaders-wgsl-tone-map'),\n};";
        assert!(main.contains(wgsl), "{main}");
        assert!(main.contains("export const SHADERS = {} as const;"));
        assert!(!main.contains("webgpu_tone_map"));
        let glsl = &modules["shaders-glsl-draw-index-tone-map"];
        assert!(glsl.contains("with DRAW_INDEX and TONE_MAP. */"));
        assert!(glsl.contains("\tcull: {},\n\tlit: {\n\t\twebgl2_draw_index_tone_map: {\n"));
    }
}
