//! The generated TypeScript module. Keys are sorted and the layout is fixed, so a check can compare
//! the module byte for byte. The layout is the one the repository's formatter (Biome) produces:
//! tabs, single quotes, every object literal expanded, and shader sources as template literals.
//!
//! Each shader is an export of its own, so a bundle keeps only the shaders that its code imports:
//! the engine's download holds none of the test shaders.

use crate::{GlslStage, Output, VariantOutput};

/// The formatter's line width, and the width it counts for one tab.
const LINE_WIDTH: usize = 100;
const TAB_WIDTH: usize = 2;

/// The header comment and the types of the records.
const PREAMBLE: &str = r"// Generated by `bun run shaders` (cargo run -p null3d-shaders --bin shader-build) from
// crates/null3d-shaders/shaders.toml and the WGSL files beside it. Do not edit this file:
// `bun run shaders:check` fails when it differs from a fresh build.

/** The WGSL bind group and binding of a resource. */
export interface ShaderBinding {
	readonly group: number;
	readonly binding: number;
}

/** A uniform block of one GLSL shader, and the WGSL uniform buffer it stands for. */
export interface GlslUniformBlock extends ShaderBinding {
	/** The block name, for `getUniformBlockIndex`. */
	readonly name: string;
}

/**
 * A texture uniform of one GLSL shader. GLSL ES 3.00 joins a texture and its sampler in one
 * uniform, so the record names the WGSL texture and the WGSL sampler.
 */
export interface GlslTexture extends ShaderBinding {
	/** The uniform name, for `getUniformLocation`. */
	readonly name: string;
	/** The sampler the shader samples the texture with, or null when it only loads texels. */
	readonly sampler: ShaderBinding | null;
}

/**
 * One GLSL ES 3.00 shader. GLSL ES 3.00 has no binding numbers, so the WebGL2 backend binds each
 * uniform block and texture by the name it has in this shader.
 */
export interface GlslStage {
	readonly source: string;
	readonly uniformBlocks: readonly GlslUniformBlock[];
	readonly textures: readonly GlslTexture[];
}

/**
 * The shaders of one render pipeline, to link into one WebGL2 program. The vertex shader moves
 * depth into GL's clip range and keeps GL's row order: the canvas shows the image the right way
 * up, a pixel read returns the bottom row first, and front faces wind counter-clockwise, as on
 * WebGPU. A vertex shader that reads the instance or draw index also declares the
 * uniform `naga_vs_first_instance`, which the backend leaves unset because WebGL2 draws have no
 * first instance.
 */
export interface GlslProgram {
	readonly vertex: GlslStage;
	readonly fragment: GlslStage;
}

/** The WGSL entry points of one render pipeline. */
export interface WgslPipeline {
	readonly vertex: string;
	readonly fragment: string;
}

/** One WGSL module for WebGPU, and the entry points of its render pipelines. */
export interface WgslShader<Pipeline extends string = string> {
	readonly source: string;
	readonly pipelines: Readonly<Record<Pipeline, WgslPipeline>>;
}

/** One variant of a shader, with its output for each backend it targets. */
export interface ShaderVariant<Pipeline extends string = string> {
	/** WGSL for WebGPU, or null when the variant does not target WebGPU. */
	readonly wgsl: WgslShader<Pipeline> | null;
	/** GLSL programs for WebGL2 by pipeline, or null when the variant does not target WebGL2. */
	readonly glsl: Readonly<Record<Pipeline, GlslProgram>> | null;
}
";

/// Renders the module: one export per shader, then `SHADERS`, which gathers them by name.
pub(crate) fn module(output: &Output) -> String {
    let mut ts = Writer::default();
    ts.out.push_str(PREAMBLE);
    for (shader, variants) in &output.shaders {
        let pipelines = output.pipelines.get(shader).map_or(&[][..], Vec::as_slice);
        ts.line("");
        ts.line(&format!(
            "/** The variants of the `{shader}` shader, by variant name. */"
        ));
        ts.open(&format!("export const {}: {{", export_name(shader)));
        for variant in variants.keys() {
            ts.variant_type(variant, pipelines);
        }
        ts.depth -= 1;
        ts.open("} = {");
        for (name, variant) in variants {
            ts.open(&format!("{name}: {{"));
            ts.variant(variant);
            ts.close("},");
        }
        ts.close("};");
    }
    ts.line("");
    ts.line("/** Every shader variant, by shader name and variant name. */");
    if output.shaders.is_empty() {
        ts.line("export const SHADERS = {} as const;");
        return ts.out;
    }
    ts.open("export const SHADERS = {");
    for shader in output.shaders.keys() {
        ts.line(&format!("{shader}: {},", export_name(shader)));
    }
    ts.close("} as const;");
    ts.out
}

/// The name of a shader's own export: its name in capitals, then `_SHADER`.
fn export_name(shader: &str) -> String {
    format!("{}_SHADER", shader.to_ascii_uppercase())
}

#[derive(Default)]
struct Writer {
    out: String,
    depth: usize,
}

impl Writer {
    fn line(&mut self, text: &str) {
        for _ in 0..self.depth {
            self.out.push('\t');
        }
        self.out.push_str(text);
        self.out.push('\n');
    }

    fn open(&mut self, text: &str) {
        self.line(text);
        self.depth += 1;
    }

    fn close(&mut self, text: &str) {
        self.depth -= 1;
        self.line(text);
    }

    /// The width the formatter measures for `text` on a line at the current depth.
    fn width(&self, text: &str) -> usize {
        self.depth * TAB_WIDTH + text.chars().count()
    }

    /// A shader source as a template literal. It starts on the key's line and ends with the
    /// closing backtick at the start of a line.
    fn template(&mut self, key: &str, source: &str) {
        for _ in 0..self.depth {
            self.out.push('\t');
        }
        self.out.push_str(key);
        self.out.push_str(": `");
        let mut chars = source.chars().peekable();
        while let Some(c) = chars.next() {
            match c {
                '\\' => self.out.push_str("\\\\"),
                '`' => self.out.push_str("\\`"),
                '$' if chars.peek() == Some(&'{') => self.out.push_str("\\$"),
                _ => self.out.push(c),
            }
        }
        self.out.push_str("`,\n");
    }

    /// The type of one variant, broken over lines the way the formatter breaks a long one.
    fn variant_type(&mut self, variant: &str, pipelines: &[String]) {
        let names: Vec<String> = pipelines.iter().map(|p| quote(p)).collect();
        let union = if names.is_empty() {
            "never".to_owned()
        } else {
            names.join(" | ")
        };
        let one_line = format!("readonly {variant}: ShaderVariant<{union}>;");
        if self.width(&one_line) <= LINE_WIDTH {
            self.line(&one_line);
            return;
        }
        self.open(&format!("readonly {variant}: ShaderVariant<"));
        if names.len() < 2 || self.width(&union) <= LINE_WIDTH {
            self.line(&union);
        } else {
            for name in &names {
                self.line(&format!("| {name}"));
            }
        }
        self.close(">;");
    }

    fn variant(&mut self, variant: &VariantOutput) {
        match &variant.wgsl {
            None => self.line("wgsl: null,"),
            Some(wgsl) => {
                self.open("wgsl: {");
                self.template("source", &wgsl.source);
                if wgsl.pipelines.is_empty() {
                    self.line("pipelines: {},");
                } else {
                    self.open("pipelines: {");
                    for (name, pipeline) in &wgsl.pipelines {
                        self.open(&format!("{name}: {{"));
                        self.line(&format!("vertex: {},", quote(&pipeline.vertex)));
                        self.line(&format!("fragment: {},", quote(&pipeline.fragment)));
                        self.close("},");
                    }
                    self.close("},");
                }
                self.close("},");
            }
        }
        match &variant.glsl {
            None => self.line("glsl: null,"),
            Some(programs) if programs.is_empty() => self.line("glsl: {},"),
            Some(programs) => {
                self.open("glsl: {");
                for (name, program) in programs {
                    self.open(&format!("{name}: {{"));
                    self.stage("vertex", &program.vertex);
                    self.stage("fragment", &program.fragment);
                    self.close("},");
                }
                self.close("},");
            }
        }
    }

    fn stage(&mut self, key: &str, stage: &GlslStage) {
        self.open(&format!("{key}: {{"));
        self.template("source", &stage.source);
        if stage.uniform_blocks.is_empty() {
            self.line("uniformBlocks: [],");
        } else {
            self.open("uniformBlocks: [");
            for block in &stage.uniform_blocks {
                self.open("{");
                self.line(&format!("name: {},", quote(&block.name)));
                self.binding(block.binding);
                self.close("},");
            }
            self.close("],");
        }
        if stage.textures.is_empty() {
            self.line("textures: [],");
        } else {
            self.open("textures: [");
            for texture in &stage.textures {
                self.open("{");
                self.line(&format!("name: {},", quote(&texture.name)));
                self.binding(texture.binding);
                match texture.sampler {
                    None => self.line("sampler: null,"),
                    Some(sampler) => {
                        self.open("sampler: {");
                        self.binding(sampler);
                        self.close("},");
                    }
                }
                self.close("},");
            }
            self.close("],");
        }
        self.close("},");
    }

    fn binding(&mut self, binding: crate::Binding) {
        self.line(&format!("group: {},", binding.group));
        self.line(&format!("binding: {},", binding.binding));
    }
}

/// A single-quoted string literal.
fn quote(text: &str) -> String {
    format!("'{}'", text.replace('\\', "\\\\").replace('\'', "\\'"))
}
