//! The generated TypeScript modules. Keys are sorted and the layout is fixed, so two builds of the
//! same inputs write the same bytes. The layout is the one the repository's formatter (Biome)
//! produces: tabs, single quotes, every object literal expanded, and shader sources as template
//! literals.
//!
//! The main module holds the types, every shader that the manifest does not load by device, and
//! the loader of the device modules. Each of those shaders is an export of its own, so a bundle
//! keeps only the shaders that its code imports: the engine's download holds none of the test
//! shaders. The shaders that load by device go into one device module for each target and each
//! value of the permutation bits that a device fixes. Each is a file of its own that the loader
//! imports on demand, so a page downloads only the builds its device draws with. The builds of a
//! feature that loads on first use go into device modules of the feature's own, one for each
//! target and each value of the device's bits that those builds vary in. A page loads one of them
//! the first time a pipeline asks for one of the feature's builds, so a page that never uses the
//! feature downloads none of them.
//!
//! Many builds share a stage's source: a vertex shader stays the same across bits that change only
//! the fragment shader. Each module writes a source that several of its builds use once, as a
//! constant at its top, and those builds name the constant. The browser then parses each text once.

use std::collections::{BTreeMap, HashMap};

use null3d_gpu::drawlist::permutation;

use crate::glsl::DEPTH_MAPPING_UNIFORM;
use crate::{FirstUseFeatures, GlslStage, Output, Target, VariantOutput};

/// The formatter's line width, and the width it counts for one tab.
const LINE_WIDTH: usize = 100;
const TAB_WIDTH: usize = 2;

/// The file name of the main module, without its extension.
pub(crate) const MAIN_MODULE: &str = "shaders";

/// The file name of the module that names the features that load on first use, without its
/// extension. The page imports it alone, so it holds no shader text.
pub(crate) const FEATURES_MODULE: &str = "shader-features";

/// The extension of each device module's file: plain JavaScript, which the main module imports by
/// address, so that a bundler copies it as it is.
pub(crate) const DEVICE_MODULE_EXTENSION: &str = "js";

/// The start of each device module's file name.
pub(crate) const DEVICE_MODULE_PREFIX: &str = "shaders-";

/// The comment at the top of every module.
const HEADER: &str = r"// Generated by `bun run shaders` (cargo run -p null3d-shaders --bin shader-build) from
// crates/null3d-shaders/shaders.toml and the WGSL files beside it. Do not edit this file: git
// ignores it, and the next build replaces it.
";

/// The types of the records.
const TYPES: &str = r"
/** The WGSL bind group and binding of a resource. */
export interface ShaderBinding {
	readonly group: number;
	readonly binding: number;
}

/** A uniform block of one GLSL shader, and the WGSL uniform buffer it stands for. */
export interface GlslUniformBlock extends ShaderBinding {
	/** The block name, for `getUniformBlockIndex`. */
	readonly name: string;
}

/**
 * A texture uniform of one GLSL shader. GLSL ES 3.00 joins a texture and its sampler in one
 * uniform, so the record names the WGSL texture and the WGSL sampler.
 */
export interface GlslTexture extends ShaderBinding {
	/** The uniform name, for `getUniformLocation`. */
	readonly name: string;
	/** The sampler the shader samples the texture with, or null when it only loads texels. */
	readonly sampler: ShaderBinding | null;
}

/**
 * One GLSL ES 3.00 shader. GLSL ES 3.00 has no binding numbers, so the WebGL2 backend binds each
 * uniform block and texture by the name it has in this shader.
 */
export interface GlslStage {
	readonly source: string;
	readonly uniformBlocks: readonly GlslUniformBlock[];
	readonly textures: readonly GlslTexture[];
}

/**
 * The shaders of one render pipeline, to link into one WebGL2 program. The vertex shader maps
 * depth through the uniform that `DEPTH_MAPPING_UNIFORM` names, and keeps GL's row order: the
 * canvas shows the image the right way up, a pixel read returns the bottom row first, and front
 * faces wind counter-clockwise, as on WebGPU. A vertex shader that reads the instance or draw
 * index also declares the uniform `naga_vs_first_instance`, which the backend leaves unset
 * because WebGL2 draws have no first instance.
 */
export interface GlslProgram {
	readonly vertex: GlslStage;
	readonly fragment: GlslStage;
}

/** The WGSL entry points of one render pipeline. */
export interface WgslPipeline {
	readonly vertex: string;
	readonly fragment: string;
}

/** One WGSL module for WebGPU, and the entry points of its render pipelines. */
export interface WgslShader<Pipeline extends string = string> {
	readonly source: string;
	readonly pipelines: Readonly<Record<Pipeline, WgslPipeline>>;
}

/** One variant of a shader, with its output for each backend it targets. */
export interface ShaderVariant<Pipeline extends string = string> {
	/**
	 * The permutation bits that the variant was built with, as a render pipeline's permutation
	 * word holds them: 0 for a variant without permutation bits.
	 */
	readonly permutation: number;
	/** WGSL for WebGPU, or null when the variant does not target WebGPU. */
	readonly wgsl: WgslShader<Pipeline> | null;
	/** GLSL programs for WebGL2 by pipeline, or null when the variant does not target WebGL2. */
	readonly glsl: Readonly<Record<Pipeline, GlslProgram>> | null;
}

/** A shader's variants by name. */
export type ShaderVariants<Pipeline extends string = string> = Readonly<
	Record<string, ShaderVariant<Pipeline>>
>;
";

/// The types of the loader tables, before them.
const LOADER_TYPE: &str = r"
/** Loaders of device modules, by the permutation bits that a device fixes. */
type DeviceModules = Readonly<Record<number, () => Promise<{ SHADERS: DeviceShaders }>>>;

/**
 * The device modules of a feature that loads on first use, for one target: the permutation bits
 * that a device fixes and that the feature's builds vary in, and the loader of the module of each
 * value of those bits.
 */
interface FirstUseFiles {
	readonly bits: number;
	readonly modules: Readonly<Record<number, () => Promise<{ SHADERS: FirstUseShaders }>>>;
}

/**
 * Imports a device module by its address. A bundler copies the file that an address names once,
 * however many bundles name it, so the page's bundle and each worker's share one copy of each
 * module. The null3D Vite plugin keeps Vite from turning a small module into a data: address,
 * which a strict Content Security Policy blocks.
 */
function importShaders<Shaders>(url: URL): Promise<{ SHADERS: Shaders }> {
	return import(/* @vite-ignore */ url.href);
}
";

/// The loaders of the device modules, after the loader tables. Each target has a table and a
/// function of its own, so a bundle that loads one target's shaders holds none of the other's.
const LOADERS: &str = r"
function loadDeviceModule(modules: DeviceModules, target: string, bits: number) {
	const load = modules[bits];
	if (!load) {
		const message = `no shader module holds the ${target} builds with permutation bits ${bits}`;
		return Promise.reject(new Error(message));
	}
	return load().then((module) => module.SHADERS);
}

/**
 * Loads the WGSL builds of the shaders that load by device, with the permutation bits `bits`,
 * which holds only bits that a device fixes. Each value of those bits is a module of its own, so a
 * page downloads one.
 */
export function loadWgslShaders(bits: number): Promise<DeviceShaders> {
	return loadDeviceModule(WGSL_MODULES, 'WGSL', bits);
}

/**
 * Loads the GLSL builds of the shaders that load by device, with the permutation bits `bits`,
 * which holds only bits that a device fixes. Each value of those bits is a module of its own, so a
 * page downloads one.
 */
export function loadGlslShaders(bits: number): Promise<DeviceShaders> {
	return loadDeviceModule(GLSL_MODULES, 'GLSL', bits);
}

/**
 * The feature that loads on first use whose device modules hold the build of `shader` with the
 * permutation word `permutation`: the shader's own feature, or else that of the word's lowest bit
 * that a feature names. Undefined for a build that the device modules of the start hold.
 */
export function firstUseFeature(shader: string, permutation: number): string | undefined {
	const feature = SHADER_FEATURES[shader];
	if (feature !== undefined) return feature;
	for (const [bit, name] of FEATURE_BITS) if ((permutation & bit) !== 0) return name;
	return undefined;
}

function loadFirstUse(
	files: Readonly<Record<string, FirstUseFiles>>,
	target: string,
	feature: string,
	bits: number,
) {
	const of = files[feature];
	const load = of?.modules[bits & of.bits];
	if (!load) {
		const message = `no shader module holds the ${target} builds of ${feature} with permutation bits ${bits}`;
		return Promise.reject(new Error(message));
	}
	return load().then((module) => module.SHADERS);
}

/**
 * Loads the WGSL builds of `feature`, a feature that loads on first use, for a device whose fixed
 * permutation bits are `bits`. Its module holds only the feature's builds.
 */
export function loadWgslFeature(feature: string, bits: number): Promise<FirstUseShaders> {
	return loadFirstUse(WGSL_FIRST_USE, 'WGSL', feature, bits);
}

/**
 * Loads the GLSL builds of `feature`, a feature that loads on first use, for a device whose fixed
 * permutation bits are `bits`. Its module holds only the feature's builds.
 */
export function loadGlslFeature(feature: string, bits: number): Promise<FirstUseShaders> {
	return loadFirstUse(GLSL_FIRST_USE, 'GLSL', feature, bits);
}

/**
 * Every shader variant, by shader name and variant name: those of this module and those of every
 * device module, the modules of features that load on first use among them, for the tests that
 * check them all.
 */
export async function everyShader(): Promise<Record<string, ShaderVariants>> {
	const every: Record<string, ShaderVariants> = { ...SHADERS };
	const loads = [
		...Object.values(WGSL_MODULES),
		...Object.values(GLSL_MODULES),
		...[...Object.values(WGSL_FIRST_USE), ...Object.values(GLSL_FIRST_USE)].flatMap((files) =>
			Object.values(files.modules),
		),
	];
	for (const load of loads) {
		for (const [name, variants] of Object.entries((await load()).SHADERS)) {
			every[name] = { ...every[name], ...variants };
		}
	}
	return every;
}
";

/// A device module: the builds of the shaders that load by device for one target, with one value
/// of the permutation bits that a device fixes. A module of a feature that loads on first use holds
/// only that feature's builds, and the modules without a feature hold the builds of the start.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct DeviceModule<'a> {
    feature: Option<&'a str>,
    target: Target,
    bits: u32,
}

impl<'a> DeviceModule<'a> {
    /// The module that holds a build of `shader`, which loads by device. Such a build has one
    /// target.
    fn of(shader: &str, variant: &VariantOutput, first_use: &'a FirstUseFeatures) -> Self {
        let target = if variant.wgsl.is_some() {
            Target::Wgsl
        } else {
            Target::Glsl
        };
        Self {
            feature: first_use.feature_of(shader, variant.permutation),
            target,
            bits: variant.permutation & permutation::DEVICE,
        }
    }

    /// The names of the module's bits, in bit order.
    fn bit_names(self) -> impl Iterator<Item = &'static str> {
        permutation::NAMES
            .into_iter()
            .filter(move |&(_, value)| self.bits & value != 0)
            .map(|(name, _)| name)
    }

    /// The file name without its extension: the prefix, the feature's name for a feature that
    /// loads on first use, the target, then each bit's name in lowercase, all joined with
    /// hyphens, such as `shaders-glsl-draw-index` or `shaders-sprites-glsl-draw-index`.
    fn stem(self) -> String {
        let mut stem = DEVICE_MODULE_PREFIX.to_owned();
        if let Some(feature) = self.feature {
            stem.push_str(&feature.replace('_', "-"));
            stem.push('-');
        }
        stem.push_str(self.target.name());
        for name in self.bit_names() {
            stem.push('-');
            stem.push_str(&name.to_ascii_lowercase().replace('_', "-"));
        }
        stem
    }
}

/// Builds by shader name, then by variant name.
type Builds<'a> = BTreeMap<&'a str, BTreeMap<&'a str, &'a VariantOutput>>;

/// The builds of the shaders that load by device, by device module. A target has a module of the
/// start for each combination of the device's bits that any of its shaders varies in, and each
/// feature that loads on first use has a module for each combination of the device's bits that
/// its builds vary in. Each module holds, of each shader, the builds of its feature, or of the
/// start, that a device with the module's bits asks for: those with the module's bits that those
/// builds vary in, so a shader whose builds vary in none is in every module of its target. Each
/// module of the start lists every shader that loads by device, with or without builds in it, and
/// a feature's module lists the shaders that have builds of the feature.
fn device_builds(output: &Output) -> BTreeMap<DeviceModule<'_>, Builds<'_>> {
    let shaders = || {
        output
            .by_device
            .iter()
            .filter_map(|shader| Some((shader.as_str(), output.shaders.get(shader)?)))
    };
    let first_use = &output.first_use;
    let mut varies: BTreeMap<(&str, Option<&str>, Target), u32> = BTreeMap::new();
    let mut groups: BTreeMap<(Option<&str>, Target), u32> = BTreeMap::new();
    for (shader, variants) in shaders() {
        for variant in variants.values() {
            let of = DeviceModule::of(shader, variant, first_use);
            *varies.entry((shader, of.feature, of.target)).or_default() |= of.bits;
            *groups.entry((of.feature, of.target)).or_default() |= of.bits;
            // A device loads a module of the start for its bits, whichever builds vary in them.
            *groups.entry((None, of.target)).or_default() |= of.bits;
        }
    }
    let mut modules = BTreeMap::new();
    for (&(feature, target), &all) in &groups {
        let mut bits = all;
        loop {
            let module = DeviceModule {
                feature,
                target,
                bits,
            };
            let mut builds = Builds::new();
            for (shader, variants) in shaders() {
                let Some(&varied) = varies.get(&(shader, feature, target)) else {
                    if feature.is_none() {
                        builds.insert(shader, BTreeMap::new());
                    }
                    continue;
                };
                let wanted = DeviceModule {
                    feature,
                    target,
                    bits: bits & varied,
                };
                builds.insert(
                    shader,
                    variants
                        .iter()
                        .filter(|(_, variant)| {
                            DeviceModule::of(shader, variant, first_use) == wanted
                        })
                        .map(|(name, variant)| (name.as_str(), variant))
                        .collect(),
                );
            }
            modules.insert(module, builds);
            if bits == 0 {
                break;
            }
            bits = (bits - 1) & all;
        }
    }
    modules
}

/// Renders every module, by file name: the main module, TypeScript, and each device module, plain
/// JavaScript.
pub(crate) fn modules(output: &Output) -> BTreeMap<String, String> {
    let devices = device_builds(output);
    let mut modules = BTreeMap::from([
        (format!("{MAIN_MODULE}.ts"), main_module(output, &devices)),
        (format!("{FEATURES_MODULE}.ts"), features_module(output)),
    ]);
    for (module, builds) in &devices {
        modules.insert(
            format!("{}.{DEVICE_MODULE_EXTENSION}", module.stem()),
            device_module(*module, builds),
        );
    }
    modules
}

/// The module that names the features that load on first use, which a page may preload: no shader
/// text, so the page that checks a preload list downloads none.
fn features_module(output: &Output) -> String {
    let mut ts = Writer::default();
    ts.out.push_str(HEADER);
    ts.line("");
    ts.line("/** The features whose shader builds load on first use, as the shader manifest names them. */");
    let features = &output.first_use;
    let names: std::collections::BTreeSet<String> = (features.shaders.values())
        .chain(features.bits.values())
        .map(|name| quote(name))
        .collect();
    let names: Vec<String> = names.into_iter().collect();
    ts.line(&format!(
        "export const SHADER_FEATURES = [{}] as const;",
        names.join(", ")
    ));
    ts.line("");
    ts.line("/**");
    ts.line(" * A feature whose shader builds load on first use, which `createEngine`'s `preload` lists.");
    ts.line(" *");
    ts.line(" * @category api/engine");
    ts.line(" */");
    ts.line("export type ShaderFeature = (typeof SHADER_FEATURES)[number];");
    ts.out
}

/// The main module: the types, one export per shader that does not load by device, `SHADERS`,
/// which gathers them by name, and the loaders of the device modules, those of the features that
/// load on first use among them.
fn main_module(output: &Output, devices: &BTreeMap<DeviceModule<'_>, Builds<'_>>) -> String {
    let mut ts = Writer::default();
    ts.out.push_str(HEADER);
    ts.out.push_str(TYPES);
    ts.line("");
    ts.line("/**");
    ts.line(
        " * The shaders that load by device, each as its variants by name. A device module holds the",
    );
    ts.line(
        " * builds of one target with one value of the permutation bits that a device fixes, and a",
    );
    ts.line(" * shader without builds there has no variants in it.");
    ts.line(" */");
    ts.open("export interface DeviceShaders {");
    for shader in &output.by_device {
        let pipelines = output.pipelines.get(shader).map_or(&[][..], Vec::as_slice);
        ts.line(&format!(
            "readonly {shader}: ShaderVariants<{}>;",
            pipeline_union(pipelines)
        ));
    }
    ts.close("}");
    ts.line("");
    ts.line(
        "/** The builds of a feature that loads on first use, in one of the feature's device modules. */",
    );
    ts.line("export type FirstUseShaders = Partial<DeviceShaders>;");
    ts.line("");
    ts.line("/**");
    ts.line(
        " * The uniform through which each GLSL vertex shader maps WebGPU's clip depth: the shader",
    );
    ts.line(" * writes `z * mapping.x + w * mapping.y` as its clip depth, where `mapping` is this vec2.");
    ts.line(" * The WebGL2 backend sets it once per program, for the depth mode it draws with.");
    ts.line(" */");
    ts.line(&format!(
        "export const DEPTH_MAPPING_UNIFORM = {};",
        quote(DEPTH_MAPPING_UNIFORM)
    ));
    let own: Vec<(&String, &BTreeMap<String, VariantOutput>)> = output
        .shaders
        .iter()
        .filter(|(shader, _)| !output.by_device.contains(*shader))
        .collect();
    ts.shared_sources(own.iter().flat_map(|(_, variants)| variants.values()));
    for &(shader, variants) in &own {
        let pipelines = output.pipelines.get(shader).map_or(&[][..], Vec::as_slice);
        ts.line("");
        ts.line(&format!(
            "/** The variants of the `{shader}` shader, by variant name. */"
        ));
        ts.open(&format!("export const {}: {{", export_name(shader)));
        for variant in variants.keys() {
            ts.variant_type(variant, pipelines);
        }
        ts.depth -= 1;
        ts.open("} = {");
        for (name, variant) in variants {
            ts.open(&format!("{name}: {{"));
            ts.variant(variant);
            ts.close("},");
        }
        ts.close("};");
    }
    ts.line("");
    ts.line("/** The variants of the shaders above, by shader name and variant name. */");
    if own.is_empty() {
        ts.line("export const SHADERS = {} as const;");
    } else {
        ts.open("export const SHADERS = {");
        for &(shader, _) in &own {
            ts.line(&format!("{shader}: {},", export_name(shader)));
        }
        ts.close("} as const;");
    }
    ts.out.push_str(LOADER_TYPE);
    for target in [Target::Wgsl, Target::Glsl] {
        let name = target.name().to_ascii_uppercase();
        let modules: Vec<DeviceModule> = devices
            .keys()
            .copied()
            .filter(|module| module.target == target && module.feature.is_none())
            .collect();
        ts.line("");
        ts.line(&format!(
            "/** The {name} device modules' loaders, by the permutation bits that a device fixes. */"
        ));
        if modules.is_empty() {
            ts.line(&format!("const {name}_MODULES: DeviceModules = {{}};"));
            continue;
        }
        ts.open(&format!("const {name}_MODULES: DeviceModules = {{"));
        for module in modules {
            ts.line(&loader_entry(module));
        }
        ts.close("};");
    }
    first_use_tables(&mut ts, &output.first_use, devices);
    ts.out.push_str(LOADERS);
    ts.out
}

/// A loader table's entry for a device module: its bits, and the import of its file by address.
fn loader_entry(module: DeviceModule) -> String {
    format!(
        "{}: () => importShaders(new URL('./{}.{DEVICE_MODULE_EXTENSION}', import.meta.url)),",
        module.bits,
        module.stem()
    )
}

/// The tables of the features that load on first use: each target's modules of each feature, the
/// feature of each shader whose builds all belong to one, and the feature of each permutation bit.
fn first_use_tables(
    ts: &mut Writer,
    first_use: &FirstUseFeatures,
    devices: &BTreeMap<DeviceModule<'_>, Builds<'_>>,
) {
    for target in [Target::Wgsl, Target::Glsl] {
        let name = target.name().to_ascii_uppercase();
        let mut features: BTreeMap<&str, (u32, Vec<DeviceModule>)> = BTreeMap::new();
        for module in devices.keys().filter(|module| module.target == target) {
            if let Some(feature) = module.feature {
                let (bits, modules) = features.entry(feature).or_default();
                *bits |= module.bits;
                modules.push(*module);
            }
        }
        let table = format!("const {name}_FIRST_USE: Readonly<Record<string, FirstUseFiles>> =");
        ts.line("");
        ts.line(&format!(
            "/** The {name} device modules of each feature that loads on first use, by feature. */"
        ));
        if features.is_empty() {
            ts.line(&format!("{table} {{}};"));
            continue;
        }
        ts.open(&format!("{table} {{"));
        for (feature, (bits, modules)) in &features {
            ts.open(&format!("{feature}: {{"));
            ts.line(&format!("bits: {bits},"));
            ts.open("modules: {");
            for module in modules {
                ts.line(&loader_entry(*module));
            }
            ts.close("},");
            ts.close("},");
        }
        ts.close("};");
    }
    ts.line("");
    ts.line(
        "/** The feature that loads on first use with every build of a shader, by shader name. */",
    );
    if first_use.shaders.is_empty() {
        ts.line("const SHADER_FEATURES: Readonly<Record<string, string>> = {};");
    } else {
        ts.open("const SHADER_FEATURES: Readonly<Record<string, string>> = {");
        for (shader, feature) in &first_use.shaders {
            ts.line(&format!("{shader}: {},", quote(feature)));
        }
        ts.close("};");
    }
    ts.line("");
    ts.line(
        "/** Each permutation bit whose builds load on first use, in bit order, with its feature. */",
    );
    let bits: Vec<String> = first_use
        .bits
        .iter()
        .map(|(bit, feature)| format!("[{bit}, {}]", quote(feature)))
        .collect();
    ts.line(&format!(
        "const FEATURE_BITS: readonly (readonly [number, string])[] = [{}];",
        bits.join(", ")
    ));
}

/// A device module: `SHADERS`, the builds of every shader that loads by device for the module's
/// target and bits, of the module's feature that loads on first use or of the start. It is plain
/// JavaScript that imports nothing; the main module's types describe it.
fn device_module(module: DeviceModule, builds: &Builds<'_>) -> String {
    let mut ts = Writer::default();
    ts.out.push_str(HEADER);
    ts.shared_sources(
        builds
            .values()
            .flat_map(|variants| variants.values().copied()),
    );
    ts.line("");
    let bits: Vec<&str> = module.bit_names().collect();
    let with = if bits.is_empty() {
        "without the bits that a device fixes".to_owned()
    } else {
        format!("with {}", bits.join(" and "))
    };
    let target = module.target.name().to_ascii_uppercase();
    match module.feature {
        None => ts.line(&format!(
            "/** The {target} builds of the shaders that load by device, {with}. */"
        )),
        Some(feature) => ts.line(&format!(
            "/** The {target} builds of `{feature}`, which load on its first use, {with}. */"
        )),
    }
    ts.open("export const SHADERS = {");
    for (shader, variants) in builds {
        if variants.is_empty() {
            ts.line(&format!("{shader}: {{}},"));
            continue;
        }
        ts.open(&format!("{shader}: {{"));
        for (name, variant) in variants {
            ts.open(&format!("{name}: {{"));
            ts.variant(variant);
            ts.close("},");
        }
        ts.close("},");
    }
    ts.close("};");
    ts.out
}

/// The union of a shader's pipeline names as a TypeScript type: `never` for none.
fn pipeline_union(pipelines: &[String]) -> String {
    if pipelines.is_empty() {
        return "never".to_owned();
    }
    let names: Vec<String> = pipelines.iter().map(|p| quote(p)).collect();
    names.join(" | ")
}

/// The name of a shader's own export: its name in capitals, then `_SHADER`.
fn export_name(shader: &str) -> String {
    format!("{}_SHADER", shader.to_ascii_uppercase())
}

#[derive(Default)]
struct Writer {
    out: String,
    depth: usize,
    /// The constant that holds each source that several builds of the module share.
    shared: HashMap<String, String>,
}

/// Every stage source of a build: its WGSL module, and each GLSL program's two shaders.
fn sources(variant: &VariantOutput) -> impl Iterator<Item = &str> {
    let wgsl = variant.wgsl.iter().map(|wgsl| wgsl.source.as_str());
    let glsl = variant.glsl.iter().flat_map(|programs| {
        programs.values().flat_map(|program| {
            [
                program.vertex.source.as_str(),
                program.fragment.source.as_str(),
            ]
        })
    });
    wgsl.chain(glsl)
}

impl Writer {
    fn line(&mut self, text: &str) {
        for _ in 0..self.depth {
            self.out.push('\t');
        }
        self.out.push_str(text);
        self.out.push('\n');
    }

    fn open(&mut self, text: &str) {
        self.line(text);
        self.depth += 1;
    }

    fn close(&mut self, text: &str) {
        self.depth -= 1;
        self.line(text);
    }

    /// The width the formatter measures for `text` on a line at the current depth.
    fn width(&self, text: &str) -> usize {
        self.depth * TAB_WIDTH + text.chars().count()
    }

    /// Writes each source that more than one of `builds` uses as a constant, in the order the
    /// builds first use them, so that `template` names the constant in its place.
    fn shared_sources<'a>(&mut self, builds: impl Iterator<Item = &'a VariantOutput>) {
        let mut uses: Vec<(&str, usize)> = Vec::new();
        let mut index: HashMap<&str, usize> = HashMap::new();
        for source in builds.flat_map(sources) {
            let at = *index.entry(source).or_insert_with(|| {
                uses.push((source, 0));
                uses.len() - 1
            });
            uses[at].1 += 1;
        }
        let mut shared = uses.into_iter().filter(|&(_, count)| count > 1).peekable();
        if shared.peek().is_none() {
            return;
        }
        self.line("");
        self.line("// Sources that several builds below share, each written once.");
        for (n, (source, _)) in shared.enumerate() {
            let name = format!("SOURCE_{n}");
            self.literal(&format!("const {name} = "), source, ";");
            self.shared.insert(source.to_owned(), name);
        }
    }

    /// A shader source under `key`: the name of its shared constant, or a template literal.
    fn template(&mut self, key: &str, source: &str) {
        match self.shared.get(source) {
            Some(name) => {
                let line = format!("{key}: {name},");
                self.line(&line);
            }
            None => self.literal(&format!("{key}: "), source, ","),
        }
    }

    /// A shader source as a template literal between `before` and `after`. It starts on the line
    /// of `before` and ends with the closing backtick at the start of a line.
    fn literal(&mut self, before: &str, source: &str, after: &str) {
        for _ in 0..self.depth {
            self.out.push('\t');
        }
        self.out.push_str(before);
        self.out.push('`');
        let mut chars = source.chars().peekable();
        while let Some(c) = chars.next() {
            match c {
                '\\' => self.out.push_str("\\\\"),
                '`' => self.out.push_str("\\`"),
                '$' if chars.peek() == Some(&'{') => self.out.push_str("\\$"),
                _ => self.out.push(c),
            }
        }
        self.out.push('`');
        self.out.push_str(after);
        self.out.push('\n');
    }

    /// The type of one variant, broken over lines the way the formatter breaks a long one.
    fn variant_type(&mut self, variant: &str, pipelines: &[String]) {
        let union = pipeline_union(pipelines);
        let one_line = format!("readonly {variant}: ShaderVariant<{union}>;");
        if self.width(&one_line) <= LINE_WIDTH {
            self.line(&one_line);
            return;
        }
        self.open(&format!("readonly {variant}: ShaderVariant<"));
        if pipelines.len() < 2 || self.width(&union) <= LINE_WIDTH {
            self.line(&union);
        } else {
            for name in pipelines {
                self.line(&format!("| {}", quote(name)));
            }
        }
        self.close(">;");
    }

    fn variant(&mut self, variant: &VariantOutput) {
        self.line(&format!("permutation: {},", variant.permutation));
        match &variant.wgsl {
            None => self.line("wgsl: null,"),
            Some(wgsl) => {
                self.open("wgsl: {");
                self.template("source", &wgsl.source);
                if wgsl.pipelines.is_empty() {
                    self.line("pipelines: {},");
                } else {
                    self.open("pipelines: {");
                    for (name, pipeline) in &wgsl.pipelines {
                        self.open(&format!("{name}: {{"));
                        self.line(&format!("vertex: {},", quote(&pipeline.vertex)));
                        self.line(&format!("fragment: {},", quote(&pipeline.fragment)));
                        self.close("},");
                    }
                    self.close("},");
                }
                self.close("},");
            }
        }
        match &variant.glsl {
            None => self.line("glsl: null,"),
            Some(programs) if programs.is_empty() => self.line("glsl: {},"),
            Some(programs) => {
                self.open("glsl: {");
                for (name, program) in programs {
                    self.open(&format!("{name}: {{"));
                    self.stage("vertex", &program.vertex);
                    self.stage("fragment", &program.fragment);
                    self.close("},");
                }
                self.close("},");
            }
        }
    }

    fn stage(&mut self, key: &str, stage: &GlslStage) {
        self.open(&format!("{key}: {{"));
        self.template("source", &stage.source);
        if stage.uniform_blocks.is_empty() {
            self.line("uniformBlocks: [],");
        } else {
            self.open("uniformBlocks: [");
            for block in &stage.uniform_blocks {
                self.open("{");
                self.line(&format!("name: {},", quote(&block.name)));
                self.binding(block.binding);
                self.close("},");
            }
            self.close("],");
        }
        if stage.textures.is_empty() {
            self.line("textures: [],");
        } else {
            self.open("textures: [");
            for texture in &stage.textures {
                self.open("{");
                self.line(&format!("name: {},", quote(&texture.name)));
                self.binding(texture.binding);
                match texture.sampler {
                    None => self.line("sampler: null,"),
                    Some(sampler) => {
                        self.open("sampler: {");
                        self.binding(sampler);
                        self.close("},");
                    }
                }
                self.close("},");
            }
            self.close("],");
        }
        self.close("},");
    }

    fn binding(&mut self, binding: crate::Binding) {
        self.line(&format!("group: {},", binding.group));
        self.line(&format!("binding: {},", binding.binding));
    }
}

/// A single-quoted string literal.
fn quote(text: &str) -> String {
    format!("'{}'", text.replace('\\', "\\\\").replace('\'', "\\'"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::WgslOutput;

    fn build(target: Target, permutation: u32) -> VariantOutput {
        let wgsl = WgslOutput {
            source: String::new(),
            pipelines: BTreeMap::new(),
        };
        VariantOutput {
            permutation,
            wgsl: (target == Target::Wgsl).then_some(wgsl),
            glsl: (target == Target::Glsl).then(BTreeMap::new),
        }
    }

    /// Two shaders that load by device, as the engine's would with tone mapping in the shader: a
    /// template that varies in both of the device's bits on WebGL2 and in tone mapping on WebGPU,
    /// and a WebGPU compute shader without bits.
    fn output() -> Output {
        use permutation::{DRAW_INDEX, TONE_MAP};
        let mut output = Output::default();
        let mut lit = BTreeMap::new();
        lit.insert("webgpu".to_owned(), build(Target::Wgsl, 0));
        lit.insert("webgpu_tone_map".to_owned(), build(Target::Wgsl, TONE_MAP));
        for (name, bits) in [
            ("webgl2", 0),
            ("webgl2_draw_index", DRAW_INDEX),
            ("webgl2_tone_map", TONE_MAP),
            ("webgl2_draw_index_tone_map", DRAW_INDEX | TONE_MAP),
        ] {
            lit.insert(name.to_owned(), build(Target::Glsl, bits));
        }
        let cull = BTreeMap::from([("webgpu".to_owned(), build(Target::Wgsl, 0))]);
        output.shaders.insert("lit".to_owned(), lit);
        output.shaders.insert("cull".to_owned(), cull);
        output.by_device = ["cull".to_owned(), "lit".to_owned()].into();
        output
    }

    fn names<'a>(builds: &Builds<'a>, shader: &str) -> Vec<&'a str> {
        builds[shader].keys().copied().collect()
    }

    #[test]
    fn each_target_has_a_module_for_each_combination_of_the_bits_its_shaders_vary_in() {
        let output = output();
        let modules = device_builds(&output);
        let stems: Vec<String> = modules.keys().map(|module| module.stem()).collect();
        assert_eq!(
            stems,
            [
                "shaders-wgsl",
                "shaders-wgsl-tone-map",
                "shaders-glsl",
                "shaders-glsl-draw-index",
                "shaders-glsl-tone-map",
                "shaders-glsl-draw-index-tone-map",
            ]
        );
        let module = |target, bits| {
            &modules[&DeviceModule {
                feature: None,
                target,
                bits,
            }]
        };
        let tone_map = permutation::TONE_MAP;
        let both = permutation::DRAW_INDEX | tone_map;
        assert_eq!(names(module(Target::Wgsl, 0), "lit"), ["webgpu"]);
        assert_eq!(
            names(module(Target::Wgsl, tone_map), "lit"),
            ["webgpu_tone_map"]
        );
        assert_eq!(
            names(module(Target::Glsl, both), "lit"),
            ["webgl2_draw_index_tone_map"]
        );
        for bits in [0, tone_map] {
            assert_eq!(names(module(Target::Wgsl, bits), "cull"), ["webgpu"]);
        }
        assert!(names(module(Target::Glsl, both), "cull").is_empty());
    }

    #[test]
    fn the_main_module_loads_each_device_module_and_holds_none_of_their_shaders() {
        let modules = modules(&output());
        assert_eq!(modules.len(), 8);
        let main = &modules["shaders.ts"];
        assert!(main.contains("\treadonly cull: ShaderVariants<never>;\n"));
        assert!(main.contains("\t3: () => importShaders(new URL('./shaders-glsl-draw-index-tone-map.js', import.meta.url)),\n"));
        let wgsl = "const WGSL_MODULES: DeviceModules = {\n\t0: () => importShaders(new URL('./shaders-wgsl.js', import.meta.url)),\n\t2: () => importShaders(new URL('./shaders-wgsl-tone-map.js', import.meta.url)),\n};";
        assert!(main.contains(wgsl), "{main}");
        assert!(main.contains("export const SHADERS = {} as const;"));
        assert!(!main.contains("webgpu_tone_map"));
        let glsl = &modules["shaders-glsl-draw-index-tone-map.js"];
        assert!(glsl.contains("with DRAW_INDEX and TONE_MAP. */"));
        assert!(glsl.contains("\tcull: {},\n\tlit: {\n\t\twebgl2_draw_index_tone_map: {\n"));
    }

    /// The shaders of [`output`], with a sprite shader whose builds all load on first use, and the
    /// lit template's BLOOM builds, which load with bloom.
    fn output_with_features() -> Output {
        use permutation::{BLOOM, DRAW_INDEX, TONE_MAP};
        let mut output = output();
        let lit = output.shaders.get_mut("lit").unwrap();
        lit.insert("webgpu_bloom".to_owned(), build(Target::Wgsl, BLOOM));
        lit.insert(
            "webgl2_draw_index_bloom".to_owned(),
            build(Target::Glsl, DRAW_INDEX | BLOOM),
        );
        let sprite = BTreeMap::from([
            ("webgpu".to_owned(), build(Target::Wgsl, 0)),
            ("webgpu_tone_map".to_owned(), build(Target::Wgsl, TONE_MAP)),
            ("webgl2".to_owned(), build(Target::Glsl, 0)),
        ]);
        output.shaders.insert("sprite".to_owned(), sprite);
        output.by_device.insert("sprite".to_owned());
        output
            .first_use
            .shaders
            .insert("sprite".to_owned(), "sprites".to_owned());
        output.first_use.bits.insert(BLOOM, "bloom".to_owned());
        output
    }

    #[test]
    fn each_feature_that_loads_on_first_use_has_modules_of_its_own_by_the_bits_its_builds_vary_in()
    {
        let output = output_with_features();
        let modules = device_builds(&output);
        let stems: Vec<String> = modules.keys().map(|module| module.stem()).collect();
        assert_eq!(
            stems,
            [
                "shaders-wgsl",
                "shaders-wgsl-tone-map",
                "shaders-glsl",
                "shaders-glsl-draw-index",
                "shaders-glsl-tone-map",
                "shaders-glsl-draw-index-tone-map",
                "shaders-bloom-wgsl",
                "shaders-bloom-glsl",
                "shaders-bloom-glsl-draw-index",
                "shaders-sprites-wgsl",
                "shaders-sprites-wgsl-tone-map",
                "shaders-sprites-glsl",
            ]
        );
        let module = |feature, target, bits| {
            &modules[&DeviceModule {
                feature,
                target,
                bits,
            }]
        };
        let start = module(None, Target::Wgsl, 0);
        assert_eq!(names(start, "lit"), ["webgpu"], "the start holds no bloom");
        assert!(names(start, "sprite").is_empty(), "nor any sprite");
        let bloom = module(Some("bloom"), Target::Glsl, permutation::DRAW_INDEX);
        assert_eq!(names(bloom, "lit"), ["webgl2_draw_index_bloom"]);
        assert!(
            !bloom.contains_key("sprite"),
            "a feature lists its own shaders"
        );
        let sprites = module(Some("sprites"), Target::Wgsl, permutation::TONE_MAP);
        assert_eq!(names(sprites, "sprite"), ["webgpu_tone_map"]);
        assert_eq!(sprites.keys().copied().collect::<Vec<_>>(), ["sprite"]);
    }

    #[test]
    fn the_main_module_finds_and_loads_the_modules_of_each_feature() {
        let modules = modules(&output_with_features());
        assert_eq!(modules.len(), 14);
        assert!(
            modules["shader-features.ts"]
                .contains("export const SHADER_FEATURES = ['bloom', 'sprites'] as const;")
        );
        let main = &modules["shaders.ts"];
        let sprites = "	sprites: {
		bits: 2,
		modules: {
			0: () => importShaders(new URL('./shaders-sprites-wgsl.js', import.meta.url)),
			2: () => importShaders(new URL('./shaders-sprites-wgsl-tone-map.js', import.meta.url)),
		},
	},
";
        assert!(main.contains(sprites), "{main}");
        assert!(main.contains(
            "			1: () => importShaders(new URL('./shaders-bloom-glsl-draw-index.js', import.meta.url)),
"
        ));
        assert!(main.contains(
            "	sprite: 'sprites',
"
        ));
        assert!(main.contains(&format!(
            "FEATURE_BITS: readonly (readonly [number, string])[] = [[{}, 'bloom']];",
            permutation::BLOOM
        )));
        let start = "const WGSL_MODULES: DeviceModules = {
	0: () => importShaders(new URL('./shaders-wgsl.js', import.meta.url)),
	2: () => importShaders(new URL('./shaders-wgsl-tone-map.js', import.meta.url)),
};";
        assert!(main.contains(start), "{main}");
        let sprites = &modules["shaders-sprites-wgsl-tone-map.js"];
        assert!(!sprites.contains("import"));
        assert!(sprites.contains(
            "export const SHADERS = {
	sprite: {
"
        ));
        assert!(modules["shaders-wgsl.js"].contains(
            "	sprite: {},
"
        ));
    }

    fn glsl_program(vertex: &str, fragment: &str) -> crate::GlslProgram {
        let stage = |source: &str| GlslStage {
            source: source.to_owned(),
            uniform_blocks: Vec::new(),
            textures: Vec::new(),
        };
        crate::GlslProgram {
            vertex: stage(vertex),
            fragment: stage(fragment),
        }
    }

    #[test]
    fn a_source_that_several_builds_of_a_module_share_is_written_once() {
        let mut output = Output::default();
        let mut lit = BTreeMap::new();
        for (name, fragment) in [("a", "frag `a` ${x}"), ("b", "frag b")] {
            let mut build = build(Target::Glsl, 0);
            build.glsl = Some(BTreeMap::from([(
                "main".to_owned(),
                glsl_program("vert shared", fragment),
            )]));
            lit.insert(name.to_owned(), build);
        }
        output.shaders.insert("lit".to_owned(), lit);
        output.by_device = ["lit".to_owned()].into();
        let modules = modules(&output);
        let glsl = &modules["shaders-glsl.js"];
        assert_eq!(glsl.matches("vert shared").count(), 1, "{glsl}");
        assert!(
            glsl.contains("\nconst SOURCE_0 = `vert shared`;\n"),
            "{glsl}"
        );
        assert_eq!(glsl.matches("source: SOURCE_0,").count(), 2, "{glsl}");
        assert!(glsl.contains("source: `frag \\`a\\` \\${x}`,"), "{glsl}");
        assert!(glsl.contains("source: `frag b`,"), "{glsl}");
        assert!(!glsl.contains("SOURCE_1"), "{glsl}");
    }
}
