//! Numbers TypeScript shares with the engine core, written out as a generated TypeScript module so
//! neither side copies them by hand.

use null3d_core::handle::{GENERATION_BITS, SLOT_BITS};
use null3d_core::layers::DEFAULT_LAYERS;
use null3d_core::lights::{color as light_color, kind as light_kind, value as light_value};
use null3d_core::scene::{NO_PARENT, flags, op};
use null3d_core::world::MATRIX_FLOATS;
use null3d_gpu::caps::Capabilities;
use null3d_gpu::drawlist::{address, filter, format, sizes, upload_flags};
use null3d_render::arrays::ArrayName;
use null3d_render::cpu_culled::{CpuCulledConfig, MAX_SOURCE_BITS};
use null3d_render::frame::{NO_MATERIAL, NO_MESH};
use null3d_render::geometry::Shape;
use null3d_render::gpu_driven::{MAX_USEFUL_BINDING_BYTES, PORTABLE_MAX_SOURCES};
use null3d_render::textures::{DEFAULT_MAX_ANISOTROPY, DEFAULT_UPLOAD_BUDGET, MAX_LAYERS};

/// Fields of `sceneArrays`.
pub mod scene_field {
    pub const POSITIONS: u32 = 0;
    pub const ROTATIONS: u32 = 1;
    pub const SCALES: u32 = 2;
    pub const LOCAL_RADII: u32 = 3;
    pub const DIRTY_WORDS: u32 = 4;
    pub const LOCAL_CENTERS: u32 = 5;
}

/// Fields of `batchArrays`.
pub mod batch_field {
    pub const POSITIONS: u32 = 0;
    pub const ROTATIONS: u32 = 1;
    pub const SCALES: u32 = 2;
    pub const COLORS: u32 = 3;
}

/// Fields of `debugLineArrays`.
pub mod debug_line_field {
    pub const POSITIONS: u32 = 0;
    pub const COLORS: u32 = 1;
}

/// Fields of `commandRing`.
pub mod ring_field {
    pub const RECORDS: u32 = 0;
    pub const CAPACITY: u32 = 1;
    pub const WRITE_INDEX: u32 = 2;
    pub const READ_INDEX: u32 = 3;
}

/// 32-bit words in one command record.
pub const COMMAND_WORDS: u32 = 4;

/// How a material shades, as `createMaterial` takes it.
pub mod shading {
    /// Lit, as three.js's `MeshLambertMaterial`.
    pub const LIT: u32 = 0;
    /// The base color only, as three.js's `MeshBasicMaterial`.
    pub const UNLIT: u32 = 1;
    /// The first texture coordinates as red and green, for the engine's own tests.
    pub const TEXCOORDS: u32 = 2;
    /// The base color times the material's map, as three.js's `MeshBasicMaterial` with a `map`.
    pub const UNLIT_MAP: u32 = 3;
}

/// The numbers that `textureStat` reads from the texture store.
pub mod texture_stat {
    /// The GPU bytes that every texture array holds, free layers included.
    pub const MEMORY_BYTES: u32 = 0;
    /// The GPU bytes of one texture: its layer, with every mip level.
    pub const TEXTURE_BYTES: u32 = 1;
    /// Texel bytes that the last recorded frame uploads.
    pub const LAST_FRAME_BYTES: u32 = 2;
    /// The most texel bytes that any frame uploaded.
    pub const LARGEST_FRAME_BYTES: u32 = 3;
    /// Textures with an image that is not on the GPU yet.
    pub const WAITING: u32 = 4;
    /// Images sent so far, which is the last image id handed out.
    pub const IMAGES_SENT: u32 = 5;
    /// The widest and tallest texture the store takes.
    pub const MAX_SIZE: u32 = 6;
}

/// The settings that `setTextureOption` changes.
pub mod texture_option {
    /// The texel bytes that one frame may upload.
    pub const UPLOAD_BUDGET: u32 = 0;
    /// The largest anisotropy that samplers use.
    pub const MAX_ANISOTROPY: u32 = 1;
    /// Any value makes the next recorded frame upload every image that arrived, whatever its
    /// budget, as a held frame must.
    pub const UPLOAD_ALL: u32 = 2;
}

/// The arrays that `createMeshFromArrays` finds in the staging words, and what it does with them.
/// The staging words hold, one after another, the positions and each array present in this
/// order, as 32-bit floats, then the indices, as 32-bit unsigned integers.
pub mod mesh_arrays {
    pub const NORMALS: u32 = 1;
    pub const UVS: u32 = 2;
    pub const UVS1: u32 = 4;
    /// Colors of three floats per vertex, or four with `COLORS_ALPHA`.
    pub const COLORS: u32 = 8;
    pub const COLORS_ALPHA: u32 = 16;
    pub const TANGENTS: u32 = 32;
    pub const INDICES: u32 = 64;
    pub const COMPUTE_NORMALS: u32 = 128;
    pub const COMPUTE_TANGENTS: u32 = 256;
}

/// The first detail of an E1206 failure: what is wrong with the arrays. The second detail is the
/// array's code, or for the last two problems the element's place.
pub mod arrays_problem {
    pub const NO_VERTICES: u32 = 1;
    pub const LENGTH: u32 = 2;
    pub const NOT_TRIANGLES: u32 = 3;
    pub const TWICE: u32 = 4;
    pub const MISSING: u32 = 5;
    /// The second detail is the place of the index in the indices.
    pub const INDEX_OUT_OF_RANGE: u32 = 6;
    /// Plus the array's code; the second detail is the place of the value in the array.
    pub const NOT_FINITE: u32 = 16;
}

/// What a per-frame count returns where the core does not count, such as visible entries where the
/// GPU culls.
pub const NOT_COUNTED: u32 = u32::MAX;

/// The generated module's text.
pub fn typescript() -> String {
    let mut out = String::from(
        "// Generated by `cargo test -p null3d-wasm` from crates/null3d-wasm/src/constants.rs.\n\
         // Do not edit: set NULL3D_UPDATE_GENERATED=1 and run that command to rewrite it.\n\n",
    );
    // A slice, not an array of a stated length, so work that adds a group changes no count.
    let groups: &[(&str, &[(&str, u32)])] = &[
        (
            "COMMAND",
            &[
                ("CREATE", op::CREATE),
                ("DESTROY", op::DESTROY),
                ("SET_PARENT", op::SET_PARENT),
                ("SET_MESH", op::SET_MESH),
                ("SET_MATERIAL", op::SET_MATERIAL),
                ("SET_DYNAMIC", op::SET_DYNAMIC),
                ("SET_VISIBLE", op::SET_VISIBLE),
                ("SET_LAYERS", op::SET_LAYERS),
                ("SET_FLAGS", op::SET_FLAGS),
                ("SET_RENDER_ORDER", op::SET_RENDER_ORDER),
                ("KEEP_WORLD", op::KEEP_WORLD),
                ("WORDS", COMMAND_WORDS),
            ],
        ),
        (
            "FLAG",
            &[
                ("DYNAMIC", flags::DYNAMIC),
                ("VISIBLE", flags::VISIBLE),
                ("CAST_SHADOWS", flags::CAST_SHADOWS),
                ("RECEIVE_SHADOWS", flags::RECEIVE_SHADOWS),
                ("UNCULLED", flags::UNCULLED),
                ("CUSTOM_BOUNDS", flags::CUSTOM_BOUNDS),
            ],
        ),
        ("LAYERS", &[("DEFAULT", DEFAULT_LAYERS)]),
        (
            "LIGHT_KIND",
            &[
                ("DIRECTIONAL", light_kind::DIRECTIONAL),
                ("POINT", light_kind::POINT),
                ("SPOT", light_kind::SPOT),
                ("HEMISPHERE", light_kind::HEMISPHERE),
                ("AMBIENT", light_kind::AMBIENT),
            ],
        ),
        (
            "LIGHT_COLOR",
            &[("MAIN", light_color::MAIN), ("GROUND", light_color::GROUND)],
        ),
        (
            "LIGHT_VALUE",
            &[
                ("INTENSITY", light_value::INTENSITY),
                ("RANGE", light_value::RANGE),
                ("DECAY", light_value::DECAY),
                ("ANGLE", light_value::ANGLE),
                ("PENUMBRA", light_value::PENUMBRA),
            ],
        ),
        (
            "SCENE_FIELD",
            &[
                ("POSITIONS", scene_field::POSITIONS),
                ("ROTATIONS", scene_field::ROTATIONS),
                ("SCALES", scene_field::SCALES),
                ("LOCAL_RADII", scene_field::LOCAL_RADII),
                ("DIRTY_WORDS", scene_field::DIRTY_WORDS),
                ("LOCAL_CENTERS", scene_field::LOCAL_CENTERS),
            ],
        ),
        (
            "BATCH_FIELD",
            &[
                ("POSITIONS", batch_field::POSITIONS),
                ("ROTATIONS", batch_field::ROTATIONS),
                ("SCALES", batch_field::SCALES),
                ("COLORS", batch_field::COLORS),
            ],
        ),
        (
            "DEBUG_LINE_FIELD",
            &[
                ("POSITIONS", debug_line_field::POSITIONS),
                ("COLORS", debug_line_field::COLORS),
            ],
        ),
        (
            "RING_FIELD",
            &[
                ("RECORDS", ring_field::RECORDS),
                ("CAPACITY", ring_field::CAPACITY),
                ("WRITE_INDEX", ring_field::WRITE_INDEX),
                ("READ_INDEX", ring_field::READ_INDEX),
            ],
        ),
        (
            "HANDLE",
            &[
                ("SLOT_BITS", SLOT_BITS),
                ("GENERATION_BITS", GENERATION_BITS),
            ],
        ),
        (
            "CORE",
            &[
                ("NO_PARENT", NO_PARENT),
                ("NO_MESH", NO_MESH),
                ("NO_MATERIAL", NO_MATERIAL),
                ("MATRIX_FLOATS", MATRIX_FLOATS as u32),
                ("NOT_COUNTED", NOT_COUNTED),
            ],
        ),
        (
            "LIMIT",
            &[
                (
                    "PORTABLE_STORAGE_BINDING_BYTES",
                    sizes::PORTABLE_STORAGE_BINDING_BYTES,
                ),
                ("MAX_USEFUL_BINDING_BYTES", MAX_USEFUL_BINDING_BYTES),
                ("INSTANCE_STRIDE", sizes::INSTANCE_STRIDE),
                ("PORTABLE_MAX_SOURCES", PORTABLE_MAX_SOURCES),
                ("MATRICES_PER_TEXTURE_ROW", sizes::MATRICES_PER_TEXTURE_ROW),
                (
                    "WEBGL2_MIN_TEXTURE_SIZE",
                    CpuCulledConfig::default().max_texture_size,
                ),
                ("WEBGL2_MAX_SOURCES", 1 << MAX_SOURCE_BITS),
            ],
        ),
        (
            "CAPABILITY",
            &[("MULTI_DRAW", Capabilities::MULTI_DRAW.0 as u32)],
        ),
        (
            "SHADING",
            &[
                ("LIT", shading::LIT),
                ("UNLIT", shading::UNLIT),
                ("TEXCOORDS", shading::TEXCOORDS),
                ("UNLIT_MAP", shading::UNLIT_MAP),
            ],
        ),
        (
            "TEXTURE_STAT",
            &[
                ("MEMORY_BYTES", texture_stat::MEMORY_BYTES),
                ("TEXTURE_BYTES", texture_stat::TEXTURE_BYTES),
                ("LAST_FRAME_BYTES", texture_stat::LAST_FRAME_BYTES),
                ("LARGEST_FRAME_BYTES", texture_stat::LARGEST_FRAME_BYTES),
                ("WAITING", texture_stat::WAITING),
                ("IMAGES_SENT", texture_stat::IMAGES_SENT),
                ("MAX_SIZE", texture_stat::MAX_SIZE),
            ],
        ),
        // The draw list's codes that `createTexture` takes, so the sketch thread needs no import of
        // the GPU layer's constants, which the bundler would put in a file of their own.
        (
            "TEXTURE",
            &[
                ("FORMAT_SRGB", format::RGBA8_UNORM_SRGB),
                ("FORMAT_LINEAR", format::RGBA8_UNORM),
                ("FORMAT_HALF_FLOAT", format::RGBA16_FLOAT),
                ("PREMULTIPLIED_ALPHA", upload_flags::PREMULTIPLIED_ALPHA),
                ("MAX_DEPTH", MAX_LAYERS),
                ("WRAP_CLAMP", address::CLAMP_TO_EDGE),
                ("WRAP_REPEAT", address::REPEAT),
                ("WRAP_MIRROR", address::MIRROR_REPEAT),
                ("FILTER_NEAREST", filter::NEAREST),
                ("FILTER_LINEAR", filter::LINEAR),
            ],
        ),
        (
            "TEXTURE_OPTION",
            &[
                ("UPLOAD_BUDGET", texture_option::UPLOAD_BUDGET),
                ("MAX_ANISOTROPY", texture_option::MAX_ANISOTROPY),
                ("UPLOAD_ALL", texture_option::UPLOAD_ALL),
                ("DEFAULT_UPLOAD_BUDGET", DEFAULT_UPLOAD_BUDGET),
                ("DEFAULT_MAX_ANISOTROPY", DEFAULT_MAX_ANISOTROPY),
            ],
        ),
        (
            "SHAPE",
            &[
                ("BOX", Shape::Box as u32),
                ("SPHERE", Shape::Sphere as u32),
                ("PLANE", Shape::Plane as u32),
                ("CYLINDER", Shape::Cylinder as u32),
                ("TORUS", Shape::Torus as u32),
                ("CAPSULE", Shape::Capsule as u32),
                ("CIRCLE", Shape::Circle as u32),
                ("RING", Shape::Ring as u32),
            ],
        ),
        (
            "MESH_ARRAYS",
            &[
                ("NORMALS", mesh_arrays::NORMALS),
                ("UVS", mesh_arrays::UVS),
                ("UVS1", mesh_arrays::UVS1),
                ("COLORS", mesh_arrays::COLORS),
                ("COLORS_ALPHA", mesh_arrays::COLORS_ALPHA),
                ("TANGENTS", mesh_arrays::TANGENTS),
                ("INDICES", mesh_arrays::INDICES),
                ("COMPUTE_NORMALS", mesh_arrays::COMPUTE_NORMALS),
                ("COMPUTE_TANGENTS", mesh_arrays::COMPUTE_TANGENTS),
            ],
        ),
        (
            "ARRAY",
            &[
                ("POSITIONS", ArrayName::Positions as u32),
                ("NORMALS", ArrayName::Normals as u32),
                ("UVS", ArrayName::Uvs as u32),
                ("UVS1", ArrayName::Uvs1 as u32),
                ("COLORS", ArrayName::Colors as u32),
                ("TANGENTS", ArrayName::Tangents as u32),
                ("INDICES", ArrayName::Indices as u32),
            ],
        ),
        (
            "ARRAYS_PROBLEM",
            &[
                ("NO_VERTICES", arrays_problem::NO_VERTICES),
                ("LENGTH", arrays_problem::LENGTH),
                ("NOT_TRIANGLES", arrays_problem::NOT_TRIANGLES),
                ("TWICE", arrays_problem::TWICE),
                ("MISSING", arrays_problem::MISSING),
                ("INDEX_OUT_OF_RANGE", arrays_problem::INDEX_OUT_OF_RANGE),
                ("NOT_FINITE", arrays_problem::NOT_FINITE),
            ],
        ),
    ];
    for &(prefix, entries) in groups {
        for (name, value) in entries {
            out.push_str(&format!("export const {prefix}_{name} = {value};\n"));
        }
        out.push('\n');
    }
    out.pop();
    out
}

#[cfg(test)]
mod tests {
    #[test]
    fn the_generated_module_is_current() {
        let path = concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../packages/engine/src/generated/core.ts"
        );
        let expected = super::typescript();
        if std::env::var_os("NULL3D_UPDATE_GENERATED").is_some() {
            std::fs::write(path, &expected).unwrap();
        }
        let actual = std::fs::read_to_string(path).unwrap_or_default();
        assert!(
            actual == expected,
            "{path} is out of date: run `NULL3D_UPDATE_GENERATED=1 cargo test -p null3d-wasm`"
        );
    }
}
