// The engine's error table: the single source for error messages and for the docs page of each code
// (docs/errors/, generated by tools/gen-docs.ts). Codes group by area: 11xx objects and handles,
// 12xx values, 13xx browsers and GPUs, 14xx setup and loading.

export interface ErrorEntry {
	/** A short name for the error. */
	title: string;
	/** What went wrong, in one or two sentences. */
	cause: string;
	/** How to fix it. */
	fix: string;
	/** A message as the engine prints it. */
	example: string;
	/** The first engine version with this error. */
	since: string;
}

export const ERRORS = {
	E1101: {
		title: 'Stale handle',
		cause: 'A call used an object after it was destroyed. Its slot may already hold a new object.',
		fix: 'Stop using an object after you call destroy() on it. Look for places that still keep a reference, such as arrays of enemies or selection state.',
		example:
			'E1101: setPosition() was called on "Crate" (slot 7), which was destroyed in frame 120.',
		since: '0.1',
	},
	E1102: {
		title: 'Too many objects',
		cause: 'The scene reached the most objects one engine holds.',
		fix: 'Use scene.createInstances() for many copies of one mesh: a batch is one object however many rows it has. Destroy objects you no longer need.',
		example: 'E1102: createMesh() failed: the scene already holds 1048575 objects.',
		since: '0.1',
	},
	E1103: {
		title: 'Object from another engine',
		cause: 'A call received an object that this engine did not create.',
		fix: 'Pass objects created by this engine. Each engine has its own scene, and objects do not move between engines.',
		example: 'E1103: setParent() got an object that is not from this engine.',
		since: '0.1',
	},
	E1203: {
		title: 'Invalid number',
		cause: 'A call received a number that is not finite, such as NaN or Infinity.',
		fix: 'Check the value computed before this call. NaN often comes from dividing zero by zero, or from normalizing a zero-length vector.',
		example:
			'E1203: setPosition() got NaN for x on "Player" (slot 12). Check the value computed before this call.',
		since: '0.1',
	},
	E1301: {
		title: 'No usable GPU path',
		cause: 'The browser offers neither WebGPU nor WebGL2 for the way the engine was asked to draw.',
		fix: 'Remove a ?gpu= switch or createEngine gpu option that forces a path this browser lacks. Update the browser, or turn on hardware acceleration in its settings.',
		example: 'E1301: no usable GPU path for ?gpu=webgpu in this browser.',
		since: '0.1',
	},
	E1401: {
		title: 'Not a game module',
		cause:
			'The module passed to createEngine as the game does not export a game as its default export.',
		fix: 'End the game module with export default defineGame(...), and pass that module to createEngine.',
		example: 'E1401: /game.ts must export default defineGame(...).',
		since: '0.1',
	},
	E1402: {
		title: 'Engine core out of date',
		cause:
			'The engine core WebAssembly file lacks functions that the TypeScript side calls, so the two come from different builds.',
		fix: 'Rebuild the engine core with bun run build, or reinstall the engine package so its parts match.',
		example: 'E1402: the threaded engine core lacks isThreadedBuild; rebuild it.',
		since: '0.1',
	},
} satisfies Record<string, ErrorEntry>;

export type ErrorCode = keyof typeof ERRORS;
