// The engine's error table: the single source for error messages and for the docs page of each code
// (docs/errors/, generated by tools/gen-docs.ts). Codes group by area: 11xx objects and handles,
// 12xx values, 13xx browsers and GPUs, 14xx setup and loading.

export interface ErrorEntry {
	/** A short name for the error. */
	title: string;
	/** What went wrong, in one or two sentences. */
	cause: string;
	/** How to fix it. */
	fix: string;
	/** A message as the engine prints it. */
	example: string;
	/** The first engine version with this error. */
	since: string;
}

export const ERRORS = {
	E1101: {
		title: 'Stale handle',
		cause: 'A call used an object after it was destroyed. Its slot may already hold a new object.',
		fix: 'Stop using an object after you call destroy() on it. Look for places that still keep a reference, such as arrays of enemies or selection state.',
		example:
			'E1101: setPosition() was called on "Crate" (slot 7), which was destroyed in frame 120.',
		since: '0.1',
	},
	E1102: {
		title: 'Too many objects',
		cause: 'The scene reached the most objects one engine holds.',
		fix: 'Use scene.createInstances() for many copies of one mesh: a batch is one object however many rows it has. Destroy objects you no longer need.',
		example: 'E1102: createMesh() failed: the scene already holds 1048575 objects.',
		since: '0.1',
	},
	E1103: {
		title: 'Object from another engine',
		cause: 'A call received an object that this engine did not create.',
		fix: 'Pass objects created by this engine. Each engine has its own scene, and objects do not move between engines.',
		example: 'E1103: setParent() got an object that is not from this engine.',
		since: '0.1',
	},
	E1104: {
		title: 'Parent loop',
		cause:
			'A call would make an object its own ancestor: the new parent is the object itself or one of its descendants.',
		fix: 'Choose a parent outside the subtree of the object. To swap two objects in a hierarchy, move one of them to the root first.',
		example:
			'E1104: setParent() on "Arm" (slot 9) would put it under its own descendant (slot 12).',
		since: '0.1',
	},
	E1105: {
		title: 'Unknown command',
		cause:
			'The engine core received a structural change it does not know, so the TypeScript side and the core come from different builds.',
		fix: 'Rebuild the engine core with bun run build, or reinstall the engine package so its parts match.',
		example: 'E1105: the engine core received command 42.',
		since: '0.1',
	},
	E1106: {
		title: 'Object not created yet',
		cause:
			'A call read world data of an object in the frame that created it. New objects join the scene when the next frame starts.',
		fix: 'Read world positions and matrices from the next frame on, for example in the next onUpdate call.',
		example: 'E1106: getWorldPosition() on "Crate" (slot 7) ran before the frame that creates it.',
		since: '0.1',
	},
	E1107: {
		title: 'Object created twice',
		cause:
			'The engine core received a second create command for one object, so the TypeScript side and the core disagree about the scene.',
		fix: 'This is an engine bug. Report it with the code that created the object.',
		example: 'E1107: the object in slot 7 was created twice.',
		since: '0.1',
	},
	E1108: {
		title: 'Value out of range',
		cause:
			'A call received a count or an index past its limit, such as a row past the capacity of an instance batch.',
		fix: 'Keep counts and indices within the capacity you created the batch with, or create a larger batch.',
		example: 'E1108: setActiveCount() got 1200, above the limit of 1000.',
		since: '0.1',
	},
	E1203: {
		title: 'Invalid number',
		cause: 'A call received a number that is not finite, such as NaN or Infinity.',
		fix: 'Check the value computed before this call. NaN often comes from dividing zero by zero, or from normalizing a zero-length vector.',
		example:
			'E1203: setPosition() got NaN for x on "Player" (slot 12). Check the value computed before this call.',
		since: '0.1',
	},
	E1204: {
		title: 'Invalid color',
		cause:
			'A call received a color that is not a hex string, a number from 0 to 0xffffff, or three numbers from 0 to 1.',
		fix: "Pass a hex string such as '#4a8cff', a number such as 0x4a8cff, or three sRGB components from 0 to 1, such as [0.29, 0.55, 1].",
		example: "E1204: createLambertMaterial() got the color 'blue-ish'.",
		since: '0.1',
	},
	E1301: {
		title: 'No usable GPU path',
		cause: 'The browser offers neither WebGPU nor WebGL2 for the way the engine was asked to draw.',
		fix: 'Remove a ?gpu= switch or createEngine gpu option that forces a path this browser lacks. Update the browser, or turn on hardware acceleration in its settings.',
		example: 'E1301: no usable GPU path for ?gpu=webgpu in this browser.',
		since: '0.1',
	},
	E1401: {
		title: 'Not a game module',
		cause:
			'The module passed to createEngine as the game does not export a game as its default export.',
		fix: 'End the game module with export default defineGame(...), and pass that module to createEngine.',
		example: 'E1401: /game.ts must export default defineGame(...).',
		since: '0.1',
	},
	E1402: {
		title: 'Engine core out of date',
		cause:
			'The engine core WebAssembly file lacks functions that the TypeScript side calls, so the two come from different builds.',
		fix: 'Rebuild the engine core with bun run build, or reinstall the engine package so its parts match.',
		example: 'E1402: the threaded engine core lacks isThreadedBuild; rebuild it.',
		since: '0.1',
	},
	E1403: {
		title: 'Engine core not ready',
		cause:
			'An engine call ran before the engine core started in this worker, or the core started twice.',
		fix: 'Create objects in the setup function you pass to defineGame, or later, never when the game module loads.',
		example: 'E1403: createMesh() ran before the engine core started.',
		since: '0.1',
	},
	E1501: {
		title: 'Render space full',
		cause:
			'The scene needs more room than the renderer set aside. The full part is the draw list, the mesh buffers, the material table or the culling pass.',
		fix: 'Share meshes and materials between objects instead of creating them per object. Draw many copies of one mesh with an instance batch.',
		example: 'E1501: materials.standard() failed: the material table is full.',
		since: '0.1',
	},
} satisfies Record<string, ErrorEntry>;

/**
 * The code of an engine error. Each code has a docs page that gives its cause and its fix.
 *
 * @category api/engine
 */
export type ErrorCode = keyof typeof ERRORS;
