// Writes the fixtures that the engine core's tests compare with, as Rust modules, from the pinned
// three.js. From the repository root:
//   bun bench/three-fixtures.ts
// - three_mesh_arrays.rs: the normals that three.js's computeVertexNormals gives and the tangents
//   that its computeTangents gives for a few small meshes, as the bits of their 32-bit floats. The
//   meshes have shared vertices, triangles of many sizes, texture coordinates that mirror and that
//   enclose no area, a triangle that repeats a vertex, and a vertex that no triangle uses.
// - three_geometry.rs: the arrays that each geometry class builds, with its defaults and with
//   arguments that reach its special cases, as counts and digests of their bits.
// - three_animation.rs (in the core's tests): a small skeleton, clips with linear and step tracks
//   on grids of 30 and 24 keys per second and at uneven times, and the local pose and skinning
//   matrices that three.js's AnimationMixer and Skeleton give for single clips and blends. Scripts
//   of plays, fades, masked layers and additive clips give the poses after chosen steps.
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import {
	AnimationClip,
	AnimationMixer,
	AnimationUtils,
	Bone,
	BoxGeometry,
	BufferAttribute,
	BufferGeometry,
	CapsuleGeometry,
	CircleGeometry,
	ConeGeometry,
	CylinderGeometry,
	Group,
	InterpolateDiscrete,
	InterpolateLinear,
	type KeyframeTrack,
	LoopOnce,
	type Matrix4,
	PlaneGeometry,
	Quaternion,
	QuaternionKeyframeTrack,
	REVISION,
	RingGeometry,
	Skeleton,
	SphereGeometry,
	TorusGeometry,
	Vector3,
	VectorKeyframeTrack,
} from 'three';

const FIXTURES = join(import.meta.dirname, '../crates/null3d-render/tests/fixtures');
const CORE_FIXTURES = join(import.meta.dirname, '../crates/null3d-core/tests/fixtures');

interface Mesh {
	name: string;
	positions: Float32Array;
	uvs: Float32Array;
	indices: number[] | null;
}

/** An uneven grid of `columns` x `rows` quads with texture coordinates that mirror halfway. */
function indexedMesh(columns: number, rows: number): Mesh {
	const positions: number[] = [];
	const uvs: number[] = [];
	for (let j = 0; j <= rows; j++) {
		for (let i = 0; i <= columns; i++) {
			positions.push(
				i + 0.3 * Math.sin(i * 1.7 + j),
				j + 0.25 * Math.cos(i + j * 2.3),
				0.4 * Math.sin(i * 0.9) * Math.cos(j * 1.1),
			);
			const u = i / columns;
			uvs.push(i * 2 <= columns ? u : 1 - u, j / rows + 0.01 * Math.sin(i * 3.1));
		}
	}
	const row = columns + 1;
	const indices: number[] = [];
	for (let j = 0; j < rows; j++) {
		for (let i = 0; i < columns; i++) {
			const a = j * row + i;
			const b = (j + 1) * row + i;
			indices.push(a, a + 1, b, b, a + 1, b + 1);
		}
	}
	// A triangle that repeats a vertex, and one whose texture coordinates enclose no area.
	indices.push(0, 0, 1);
	uvs.push(0.5, 0.5, 0.5, 0.5, 0.5, 0.5);
	positions.push(0.1, 0.2, 0.3, 1.1, 0.4, -0.2, 0.3, 1.5, 0.7);
	const flat = positions.length / 3 - 3;
	indices.push(flat, flat + 1, flat + 2);
	// A vertex that no triangle uses.
	positions.push(9, 9, 9);
	uvs.push(0.25, 0.75);
	return {
		name: 'INDEXED',
		positions: new Float32Array(positions),
		uvs: new Float32Array(uvs),
		indices,
	};
}

/** Triangles without indices: three vertices each, one of them with a repeated position. */
function soup(): Mesh {
	const positions = [
		0, 0, 0, 1.3, 0.1, 0.2, 0.2, 1.1, -0.4, 2, 0.5, 1, 2.7, 1.9, 0.3, 1.1, 2.3, 0.8, 3, 3, 3, 3, 3,
		3, 4, 1, 0,
	];
	const uvs: number[] = [];
	for (let k = 0; k < positions.length; k += 3)
		uvs.push((positions[k] as number) / 4, (positions[k + 1] as number) / 4);
	return {
		name: 'SOUP',
		positions: new Float32Array(positions),
		uvs: new Float32Array(uvs),
		indices: null,
	};
}

/** The words of 32-bit values. */
function words(values: Float32Array | Uint32Array | Uint16Array): Uint32Array {
	return values instanceof Uint16Array
		? Uint32Array.from(values)
		: new Uint32Array(values.buffer, values.byteOffset, values.length);
}

/** The bits of 32-bit values, as a Rust array literal. */
function bits(values: Float32Array | Uint32Array): string {
	const hex = Array.from(words(values), (w) => `0x${w.toString(16).padStart(8, '0')}`);
	const lines: string[] = [];
	for (let k = 0; k < hex.length; k += 6) lines.push(`    ${hex.slice(k, k + 6).join(', ')},`);
	return `[\n${lines.join('\n')}\n]`;
}

function constant(name: string, values: Float32Array | Uint32Array): string {
	return `pub const ${name}: [u32; ${values.length}] = ${bits(values)};\n`;
}

function meshArraysFixture(): string {
	let out = `// Generated by \`bun bench/three-fixtures.ts\` with three.js r${REVISION}: the bits of each mesh's\n// 32-bit positions, texture coordinates and indices, and of the normals and tangents that three.js\n// computes for them. Do not edit; run the script again.\n#![allow(dead_code)]\n`;
	for (const mesh of [indexedMesh(6, 4), soup()]) {
		const geometry = new BufferGeometry();
		geometry.setAttribute('position', new BufferAttribute(mesh.positions, 3));
		geometry.setAttribute('uv', new BufferAttribute(mesh.uvs, 2));
		if (mesh.indices) geometry.setIndex(mesh.indices);
		geometry.computeVertexNormals();
		const normals = geometry.getAttribute('normal').array as Float32Array;
		out += `\npub mod ${mesh.name.toLowerCase()} {\n`;
		out += constant('POSITIONS', mesh.positions);
		out += constant('UVS', mesh.uvs);
		out += constant('NORMALS', normals);
		if (mesh.indices) {
			// three.js computes tangents only for meshes with indices.
			geometry.computeTangents();
			out += constant('INDICES', new Uint32Array(mesh.indices));
			out += constant('TANGENTS', geometry.getAttribute('tangent').array as Float32Array);
		}
		out += '}\n';
	}
	return out;
}

/** A three.js geometry, which keeps its constructor's arguments in `parameters`. */
type Generated = BufferGeometry & { parameters: Record<string, number | boolean> };
/** A geometry class of three.js. */
type GeometryClass = new (...args: never[]) => Generated;

/** Each class, and the engine's generator that builds its meshes. */
const GENERATORS = new Map<GeometryClass, string>([
	[BoxGeometry, 'box'],
	[SphereGeometry, 'sphere'],
	[PlaneGeometry, 'plane'],
	[CylinderGeometry, 'cylinder'],
	[ConeGeometry, 'cylinder'],
	[TorusGeometry, 'torus'],
	[CapsuleGeometry, 'capsule'],
	[CircleGeometry, 'circle'],
	[RingGeometry, 'ring'],
]);

/**
 * Each class with its defaults, then with arguments that reach its special cases: segment counts
 * that round down, partial arcs, open ends, points, poles away from the sphere's ends, and heights
 * of 0 and below.
 */
const GENERATOR_CASES: [GeometryClass, (number | boolean)[]][] = [
	[BoxGeometry, []],
	[BoxGeometry, [2, 0.5, 1.5, 3, 2, 4]],
	[BoxGeometry, [1, 1, 0]],
	[SphereGeometry, []],
	[SphereGeometry, [0.7, 7.6, 5, 0.3, 4, 0.4, 1.9]],
	[SphereGeometry, [2, 3, 2, 0, Math.PI * 2, 1, 3]],
	[PlaneGeometry, []],
	[PlaneGeometry, [3, 2, 4, 3]],
	[CylinderGeometry, []],
	[CylinderGeometry, [0.5, 1.2, 2, 7, 3, true, 0.3, 4.1]],
	[CylinderGeometry, [0.8, 0, 1.5, 5, 2]],
	[ConeGeometry, []],
	[ConeGeometry, [0.6, 2, 6, 3, false, 1, 3]],
	[TorusGeometry, []],
	[TorusGeometry, [2, 0.25, 5, 9, 3.5, 0.5, 4.2]],
	[CapsuleGeometry, []],
	[CapsuleGeometry, [0.5, 2, 3, 7, 4]],
	[CapsuleGeometry, [0.4, -1, 2, 5]],
	[CircleGeometry, []],
	[CircleGeometry, [2.5, 5, 0.5, 3]],
	[RingGeometry, []],
	[RingGeometry, [0.2, 1.4, 6, 3, 1, 4]],
];

/** FNV-1a over the little-endian bytes of 32-bit words, as a Rust literal. */
function digest(values: Float32Array | Uint32Array | Uint16Array): string {
	const w = words(values);
	let hash = 0xcbf29ce484222325n;
	for (const byte of new Uint8Array(w.buffer, w.byteOffset, w.byteLength))
		hash = ((hash ^ BigInt(byte)) * 0x100000001b3n) & 0xffffffffffffffffn;
	return `0x${hash.toString(16).padStart(16, '0')}`;
}

/** The bits of a 64-bit float, as a Rust literal. */
function float64(value: number): string {
	const view = new DataView(new ArrayBuffer(8));
	view.setFloat64(0, value);
	return `0x${view.getBigUint64(0).toString(16).padStart(16, '0')}`;
}

function geometryFixture(): string {
	let out = `// Generated by \`bun bench/three-fixtures.ts\` with three.js r${REVISION}: the arrays that each\n// geometry class builds, with its defaults and with other arguments. Do not edit; run the script\n// again.\n#![allow(dead_code)]\n\n`;
	out += `/// One mesh as a three.js geometry class builds it.
pub struct Case {
    /// The class and the arguments it was given.
    pub name: &'static str,
    /// The engine's generator that builds the same mesh.
    pub shape: &'static str,
    /// The bits of the constructor's arguments as 64-bit floats, in their order, with booleans as
    /// 1 or 0 and zeros after the last. A cone's are those of its cylinder, whose top radius is 0.
    pub args: [u64; 8],
    pub vertices: usize,
    pub indices: usize,
    /// FNV-1a digests of the bits of the 32-bit positions, normals, texture coordinates and
    /// indices.
    pub positions: u64,
    pub normals: u64,
    pub uvs: u64,
    pub triangles: u64,
}\n\n`;
	out += `pub const CASES: [Case; ${GENERATOR_CASES.length}] = [\n`;
	for (const [Class, given] of GENERATOR_CASES) {
		const make = Class as unknown as new (...args: (number | boolean)[]) => Generated;
		const geometry = new make(...given);
		const args = Object.values(geometry.parameters).map(Number);
		if (Class === ConeGeometry) args.unshift(0);
		while (args.length < 8) args.push(0);
		const attribute = (name: string) => geometry.getAttribute(name).array as Float32Array;
		const index = geometry.getIndex()?.array as Uint16Array | Uint32Array;
		out += `    Case {
        name: "new ${Class.name}(${given.join(', ')})",
        shape: "${GENERATORS.get(Class)}",
        args: [${args.map(float64).join(', ')}],
        vertices: ${geometry.getAttribute('position').count},
        indices: ${index.length},
        positions: ${digest(attribute('position'))},
        normals: ${digest(attribute('normal'))},
        uvs: ${digest(attribute('uv'))},
        triangles: ${digest(index)},
    },\n`;
	}
	return `${out}];\n`;
}

/** One joint of the animation fixture's skeleton: parent, translation, rotation and scale. */
interface Joint {
	parent: number;
	translation: [number, number, number];
	/** An axis and an angle in radians. */
	rotation: [number, number, number, number];
	scale: [number, number, number];
}

/**
 * A small character: a spine with a head, an arm and a leg. One rest rotation is near a half turn,
 * and the hand has a scale that differs per axis.
 */
const JOINTS: Joint[] = [
	{ parent: -1, translation: [0, 1, 0], rotation: [0, 1, 0, 0], scale: [1, 1, 1] },
	{ parent: 0, translation: [0, 0.5, 0], rotation: [1, 0, 0, 0.1], scale: [1, 1, 1] },
	{ parent: 1, translation: [0, 0.5, 0], rotation: [0, 0, 1, -0.2], scale: [1, 1, 1] },
	{ parent: 2, translation: [0, 0.4, 0.05], rotation: [0, 1, 0, 0.3], scale: [0.9, 0.9, 0.9] },
	{ parent: 2, translation: [0.3, 0.3, 0], rotation: [0, 0, 1, 1.2], scale: [1, 1, 1] },
	{ parent: 4, translation: [0, 0.6, 0], rotation: [0, 1, 0, 0], scale: [1, 1.2, 1] },
	{ parent: 0, translation: [0.15, -0.1, 0], rotation: [1, 0, 0, 3], scale: [1, 1, 1] },
	{ parent: 6, translation: [0, 0.8, 0], rotation: [1, 0, 0, -0.5], scale: [1, 1, 1] },
];

/** A unit quaternion `(x, y, z, w)` that turns `angle` radians about an axis. */
function axisAngle(x: number, y: number, z: number, angle: number): number[] {
	const q = new Quaternion().setFromAxisAngle(new Vector3(x, y, z).normalize(), angle);
	return [q.x, q.y, q.z, q.w].map(Math.fround);
}

interface Track {
	joint: number;
	channel: 'translation' | 'rotation' | 'scale';
	step: boolean;
	times: number[];
	values: number[];
}

/** Keys of `channel` on `joint` at each of `times`, from a function of time. */
function track(
	joint: number,
	channel: Track['channel'],
	times: number[],
	value: (t: number) => number[],
	step = false,
): Track {
	return {
		joint,
		channel,
		step,
		times: times.map(Math.fround),
		values: times.flatMap((t) => value(Math.fround(t)).map(Math.fround)),
	};
}

/** `count + 1` key times from 0 at `rate` keys per second. */
const grid = (rate: number, count: number) => Array.from({ length: count + 1 }, (_, k) => k / rate);

const TAU = Math.PI * 2;

/**
 * The clips. "grid30" has keys every thirtieth of a second, a constant rotation, a constant
 * translation away from the rest pose, a joint no track moves, and a step track. "uneven" has keys
 * at uneven times, a step track, and a rotation whose next key is stored negated. "grid24" has
 * keys every 24th of a second.
 */
const CLIPS: { name: string; tracks: Track[] }[] = [
	{
		name: 'grid30',
		tracks: [
			track(0, 'translation', grid(30, 30), (t) => [
				0.2 * Math.sin(TAU * t),
				1 + 0.1 * Math.cos(TAU * t),
				0.5 * t,
			]),
			track(1, 'rotation', grid(30, 30), (t) => axisAngle(1, 0, 0, 0.1 + 0.4 * Math.sin(TAU * t))),
			track(2, 'rotation', grid(30, 30), (t) => axisAngle(0.3, 1, 0.2, 1.5 * t)),
			track(3, 'rotation', grid(30, 30), () => axisAngle(0, 1, 0, 0.7)),
			track(4, 'rotation', grid(30, 30), (t) => axisAngle(0, 0, 1, 1.2 + 2.5 * Math.sin(TAU * t))),
			track(5, 'scale', grid(30, 30), (t) => [1 + 0.3 * t, 1.2, 1 - 0.2 * t]),
			track(5, 'translation', grid(30, 30), () => [0, 0.7, 0]),
			track(
				7,
				'rotation',
				grid(30, 30),
				(t) => axisAngle(1, 0, 0, -0.5 - Math.floor(t * 6) * 0.1),
				true,
			),
		],
	},
	{
		name: 'uneven',
		tracks: [
			track(0, 'translation', [0, 0.13, 0.41, 0.9, 1.37], (t) => [t, 1 - 0.2 * t * t, -0.3 * t]),
			track(1, 'rotation', [0, 0.13, 0.41, 0.9, 1.37], (t) =>
				axisAngle(0.2, 0.1, 1, 0.8 * Math.sin(3 * t)),
			),
			track(4, 'rotation', [0, 0.5, 1], (t) => axisAngle(0, 0, 1, 1.2 + t), true),
			{
				...track(6, 'rotation', [0, 0.6, 1.2], (t) => axisAngle(1, 0, 0, 3 + 0.5 * t)),
				// The second key negated: the same rotation, on the other side of the sphere.
				values: [
					...axisAngle(1, 0, 0, 3),
					...axisAngle(1, 0, 0, 3.3).map((v) => -v),
					...axisAngle(1, 0, 0, 3.6),
				],
			},
		],
	},
	{
		name: 'grid24',
		tracks: [
			track(0, 'translation', grid(24, 18), (t) => [0.1 * t, 1 + 0.05 * Math.sin(TAU * t), 0]),
			track(2, 'rotation', grid(24, 18), (t) => axisAngle(0, 1, 0, -0.2 + 2 * t * t)),
		],
	},
];

/** The uneven clip's frame times once resampled at 30 keys per second: 42 intervals over 1.37 s. */
const unevenFrame = (k: number) => (k * 1.37) / 42;

/**
 * Each case blends its clips at their times and weights. The uneven clip is sampled on the
 * resampled frames, where resampling loses nothing.
 */
const CASES: { name: string; samples: [clip: number, time: number, weight: number][] }[] = [
	{ name: 'rest', samples: [] },
	{ name: 'grid30 at 0', samples: [[0, 0, 1]] },
	{ name: 'grid30 at 0.37', samples: [[0, 0.37, 1]] },
	{ name: 'grid30 at 0.5', samples: [[0, 0.5, 1]] },
	{ name: 'grid30 at 0.71', samples: [[0, 0.71, 1]] },
	{ name: 'grid30 at its end', samples: [[0, 1, 1]] },
	{ name: 'grid30 past its end', samples: [[0, 1.4, 1]] },
	{ name: 'uneven at frame 0', samples: [[1, unevenFrame(0), 1]] },
	{ name: 'uneven at frame 5', samples: [[1, unevenFrame(5), 1]] },
	{ name: 'uneven at frame 19', samples: [[1, unevenFrame(19), 1]] },
	{ name: 'uneven at frame 33', samples: [[1, unevenFrame(33), 1]] },
	{ name: 'uneven at its end', samples: [[1, 1.37, 1]] },
	{ name: 'grid24 at 0.3', samples: [[2, 0.3, 1]] },
	{ name: 'grid24 at 0.61', samples: [[2, 0.61, 1]] },
	{
		name: 'grid30 and grid24, weights 0.6 and 0.4',
		samples: [
			[0, 0.37, 0.6],
			[2, 0.2, 0.4],
		],
	},
	{ name: 'grid30 at weight 0.5, with the rest pose', samples: [[0, 0.8, 0.5]] },
	{
		name: 'grid30 and grid24, weights 0.7 each',
		samples: [
			[0, 0.1, 0.7],
			[2, 0.5, 0.7],
		],
	},
	{
		name: 'three clips, weights 0.5, 0.3 and 0.2',
		samples: [
			[0, 0.62, 0.5],
			[1, unevenFrame(12), 0.3],
			[2, 0.45, 0.2],
		],
	},
];

/** A number as a Rust float literal. */
function float(value: number): string {
	const text = String(value);
	return /[.e]/.test(text) ? text : `${text}.0`;
}

/** Numbers as a Rust array literal of floats. */
function floats(values: number[], perRow: number, indent = '    '): string {
	const lines: string[] = [];
	for (let k = 0; k < values.length; k += perRow)
		lines.push(
			`${indent}${values
				.slice(k, k + perRow)
				.map(float)
				.join(', ')},`,
		);
	return `[\n${lines.join('\n')}\n${indent.slice(4)}]`;
}

/** The skeleton's bones under a group at the origin, at rest, with their world matrices. */
function buildBones(): { group: Group; bones: Bone[] } {
	const group = new Group();
	const bones: Bone[] = [];
	for (const [j, joint] of JOINTS.entries()) {
		const bone = new Bone();
		bone.name = `joint${j}`;
		bone.position.fromArray(joint.translation.map(Math.fround));
		bone.quaternion.fromArray(axisAngle(...joint.rotation));
		bone.scale.fromArray(joint.scale.map(Math.fround));
		(joint.parent < 0 ? group : bones[joint.parent])?.add(bone);
		bones.push(bone);
	}
	group.updateMatrixWorld(true);
	return { group, bones };
}

function threeClip(clip: (typeof CLIPS)[number]): AnimationClip {
	const tracks: KeyframeTrack[] = clip.tracks.map((t) => {
		const name = `joint${t.joint}.${t.channel === 'translation' ? 'position' : t.channel === 'rotation' ? 'quaternion' : 'scale'}`;
		const interpolation = t.step ? InterpolateDiscrete : InterpolateLinear;
		return t.channel === 'rotation'
			? new QuaternionKeyframeTrack(name, t.times, t.values, interpolation)
			: new VectorKeyframeTrack(name, t.times, t.values, interpolation);
	});
	return new AnimationClip(clip.name, -1, tracks);
}

/** A row-major 3 × 4 matrix from a column-major 4 × 4 matrix's elements at `at`. */
function rows(elements: ArrayLike<number>, at = 0): number[] {
	const e = (row: number, column: number) => elements[at + column * 4 + row] as number;
	return [0, 1, 2].flatMap((r) => [e(r, 0), e(r, 1), e(r, 2), e(r, 3)]);
}

function animationFixture(): string {
	const clips = CLIPS.map(threeClip);
	let out = `// Generated by \`bun bench/three-fixtures.ts\` with three.js r${REVISION}: a skeleton, clips, and the\n// local pose and skinning matrices that three.js's AnimationMixer and Skeleton give for single clips\n// and blends. Do not edit; run the script again.\n// The 32-bit inputs are written with the digits of their 64-bit value, which parses to the same\n// float.\n#![allow(dead_code, clippy::excessive_precision)]\n\n`;
	const { bones: restBones } = buildBones();
	const inverses = new Skeleton(restBones).boneInverses;
	const binds = inverses.flatMap((m) => rows(m.elements));
	out += `pub const PARENTS: [u32; ${JOINTS.length}] = [${JOINTS.map((j) => (j.parent < 0 ? 'u32::MAX' : j.parent)).join(', ')}];\n`;
	// The data stays in rows of a few numbers, which rustfmt would put one per line.
	out += `/// Translation, rotation and scale of each joint at rest.\n#[rustfmt::skip]\npub const REST: [f32; ${JOINTS.length * 10}] = ${floats(
		restBones.flatMap((b) => [
			...b.position.toArray(),
			...b.quaternion.toArray(),
			...b.scale.toArray(),
		]),
		10,
	)};\n`;
	out += `/// The inverse bind matrix of each joint, row-major 3 × 4.\n#[rustfmt::skip]\npub const INVERSE_BIND: [f32; ${JOINTS.length * 12}] = ${floats(binds.map(Math.fround), 12)};\n\n`;
	out += `/// A track as a file holds it. Channel 0 is translation, 1 rotation, 2 scale.
pub struct Track {
    pub joint: u32,
    pub channel: u32,
    pub step: bool,
    pub times: &'static [f32],
    pub values: &'static [f32],
}

pub struct Clip {
    pub name: &'static str,
    pub duration: f32,
    pub tracks: &'static [Track],
}

#[rustfmt::skip]
pub const CLIPS: [Clip; ${CLIPS.length}] = [\n`;
	const nested = ' '.repeat(20);
	CLIPS.forEach((clip, c) => {
		out += `    Clip {\n        name: "${clip.name}",\n        duration: ${float(clips[c]?.duration ?? 0)},\n        tracks: &[\n`;
		for (const t of clip.tracks) {
			const channel = ['translation', 'rotation', 'scale'].indexOf(t.channel);
			out += `            Track {\n                joint: ${t.joint},\n                channel: ${channel},\n                step: ${t.step},\n`;
			const perKey = t.channel === 'rotation' ? 4 : 3;
			out += `                times: &${floats(t.times, 8, nested)},\n`;
			out += `                values: &${floats(t.values, 2 * perKey, nested)},\n            },\n`;
		}
		out += '        ],\n    },\n';
	});
	out += `];

/// One case: clips blended at times and weights, and what three.js gives for each joint.
pub struct Case {
    pub name: &'static str,
    /// The clip, its time in seconds and its weight.
    pub samples: &'static [(usize, f32, f32)],
    /// Translation, rotation and scale of each joint.
    pub pose: [f64; ${JOINTS.length * 10}],
    /// The skinning matrix of each joint, row-major 3 × 4.
    pub skin: [f64; ${JOINTS.length * 12}],
}

#[rustfmt::skip]
pub static CASES: [Case; ${CASES.length}] = [\n`;
	const inCase = ' '.repeat(12);
	for (const c of CASES) {
		const { group, bones } = buildBones();
		const skeleton = new Skeleton(
			bones,
			inverses.map((m) => m.clone()),
		);
		const mixer = new AnimationMixer(group);
		for (const [clip, time, weight] of c.samples) {
			const action = mixer.clipAction(clips[clip] as AnimationClip);
			action.play();
			action.setEffectiveWeight(Math.fround(weight));
			action.time = Math.fround(time);
		}
		mixer.update(0);
		group.updateMatrixWorld(true);
		skeleton.update();
		const pose = bones.flatMap((b) => [
			...b.position.toArray(),
			...b.quaternion.toArray(),
			...b.scale.toArray(),
		]);
		const skin = bones.flatMap((_, j) => rows(skeleton.boneMatrices as Float32Array, j * 16));
		const samples = c.samples.map(
			([clip, time, weight]) =>
				`(${clip}, ${float(Math.fround(time))}, ${float(Math.fround(weight))})`,
		);
		out += `    Case {\n        name: "${c.name}",\n        samples: &[${samples.join(', ')}],\n`;
		out += `        pose: ${floats(pose, 10, inCase)},\n        skin: ${floats(skin, 12, inCase)},\n    },\n`;
	}
	return `${out}];\n${scriptsFixture(clips, inverses)}`;
}

/** The step of every script: one frame at 60 frames per second, as a 32-bit float. */
const SCRIPT_STEP = Math.fround(1 / 60);

/** The joints below joint 2 and joint 2 itself: the arm and the head, for masks. */
const UPPER = [2, 3, 4, 5];

/**
 * A mixer driven by a script: plays clips as the core's animator does, steps the mixer, and records
 * the pose at checkpoints and the loop and finished events.
 */
interface ScriptRun {
	mixer: AnimationMixer;
	clips: AnimationClip[];
	/** A copy of a clip with only the tracks whose joint passes `keep`. */
	filtered(clip: number, keep: (joint: number) => boolean): AnimationClip;
	/** Steps the mixer `steps` times, then records the pose. */
	check(steps: number): void;
}

/**
 * Each script plays clips through three.js's mixer as the named animator calls would, and checks
 * the pose after some steps. The core's tests repeat each script with the animator's calls.
 * Checkpoints avoid the times where grid30's step track changes key, every sixth of a second:
 * there, rounding in the sum of the steps decides which key applies.
 */
const SCRIPTS: { name: string; run(s: ScriptRun): void }[] = [
	{
		// play('grid30'), then 24 steps later play('grid24', { fade: 0.3 }).
		name: 'crossfade',
		run({ mixer, clips, check }) {
			const from = mixer.clipAction(clips[0] as AnimationClip).play();
			check(24);
			const to = mixer.clipAction(clips[2] as AnimationClip).play();
			from.crossFadeTo(to, Math.fround(0.3), false);
			check(6);
			check(6);
			check(12);
		},
	},
	{
		// play('grid24', { fade: 0.5 }) from the rest pose.
		name: 'fade in',
		run({ mixer, clips, check }) {
			mixer
				.clipAction(clips[2] as AnimationClip)
				.fadeIn(Math.fround(0.5))
				.play();
			check(12);
			check(28);
		},
	},
	{
		// setTimeScale(0.5), then play('grid30', { fade: 0.4 }).
		name: 'time scale',
		run({ mixer, clips, check }) {
			mixer.timeScale = Math.fround(0.5);
			mixer
				.clipAction(clips[0] as AnimationClip)
				.fadeIn(Math.fround(0.4))
				.play();
			check(24);
			check(30);
		},
	},
	{
		// play('grid24', { loop: false, speed: 1.5 }): it ends after 0.5 s and holds its last frame.
		name: 'once',
		run({ mixer, clips, check }) {
			const action = mixer.clipAction(clips[2] as AnimationClip);
			action.setLoop(LoopOnce, 1);
			action.clampWhenFinished = true;
			action.timeScale = Math.fround(1.5);
			action.play();
			check(20);
			check(20);
		},
	},
	{
		// play('grid24') for 150 steps: three loops.
		name: 'loops',
		run({ mixer, clips, check }) {
			mixer.clipAction(clips[2] as AnimationClip).play();
			check(150);
		},
	},
	{
		// play('grid30'); play('grid24', { layer: 1 }); setLayerMask(1, 'joint2');
		// setLayerWeight(1, 0.5). In three.js: the layer's clip keeps the masked joints' tracks, at
		// the weight that gives the layer half the pose.
		name: 'masked layer',
		run({ mixer, clips, filtered, check }) {
			mixer.clipAction(clips[0] as AnimationClip).play();
			mixer.clipAction(filtered(2, (j) => UPPER.includes(j))).play();
			check(21);
		},
	},
	{
		// As 'masked layer' with the layer's weight at 1: the layer replaces the masked joints'
		// channels that it moves.
		name: 'masked layer at full weight',
		run({ mixer, clips, filtered, check }) {
			const upperOf = (j: number) => UPPER.includes(j);
			const grid24 = clips[2] as AnimationClip;
			const replaced = new Set(
				grid24.tracks.filter((t) => upperOf(Number(t.name.match(/\d+/)?.[0]))).map((t) => t.name),
			);
			const base = clips[0] as AnimationClip;
			const kept = base.tracks.filter((t) => !replaced.has(t.name));
			mixer.clipAction(new AnimationClip('base', -1, kept)).play();
			mixer.clipAction(filtered(2, upperOf)).play();
			check(21);
		},
	},
	{
		// play('grid30'); setLayerMask(0, every joint but those below joint 4): they keep the rest
		// pose.
		name: 'masked base layer',
		run({ mixer, filtered, check }) {
			mixer.clipAction(filtered(0, (j) => j !== 4 && j !== 5)).play();
			check(21);
		},
	},
	{
		// play('grid24'); play('grid30', { layer: 1, additive: true }); setLayerWeight(1, 0.5).
		name: 'additive',
		run({ mixer, clips, check }) {
			mixer.clipAction(clips[2] as AnimationClip).play();
			const additive = AnimationUtils.makeClipAdditive((clips[0] as AnimationClip).clone());
			mixer.clipAction(additive).setEffectiveWeight(Math.fround(0.5)).play();
			check(15);
			check(18);
		},
	},
];

function scriptsFixture(clips: AnimationClip[], inverses: Matrix4[]): string {
	let out = `
/// A script's checkpoint: the steps since the one before, then what three.js gives for each
/// joint.
pub struct Check {
    pub steps: u32,
    /// Translation, rotation and scale of each joint.
    pub pose: [f64; ${JOINTS.length * 10}],
    /// The skinning matrix of each joint, row-major 3 × 4.
    pub skin: [f64; ${JOINTS.length * 12}],
}

/// A script of animator calls, which the tests make by name, and its checkpoints.
pub struct Script {
    pub name: &'static str,
    /// The seconds of each step.
    pub step: f32,
    pub checks: &'static [Check],
    /// The loop and finished events of the whole script.
    pub loops: u32,
    pub finished: u32,
}

#[rustfmt::skip]
pub static SCRIPTS: [Script; ${SCRIPTS.length}] = [\n`;
	const inCheck = ' '.repeat(16);
	for (const script of SCRIPTS) {
		const { group, bones } = buildBones();
		const skeleton = new Skeleton(
			bones,
			inverses.map((m) => m.clone()),
		);
		const mixer = new AnimationMixer(group);
		let loops = 0;
		let finished = 0;
		mixer.addEventListener('loop', () => loops++);
		mixer.addEventListener('finished', () => finished++);
		const checks: string[] = [];
		script.run({
			mixer,
			clips,
			filtered(clip, keep) {
				const source = clips[clip] as AnimationClip;
				const tracks = source.tracks.filter((t) => keep(Number(t.name.match(/\d+/)?.[0])));
				return new AnimationClip(`${source.name} filtered`, -1, tracks);
			},
			check(steps) {
				for (let k = 0; k < steps; k++) mixer.update(SCRIPT_STEP);
				group.updateMatrixWorld(true);
				skeleton.update();
				const pose = bones.flatMap((b) => [
					...b.position.toArray(),
					...b.quaternion.toArray(),
					...b.scale.toArray(),
				]);
				const skin = bones.flatMap((_, j) => rows(skeleton.boneMatrices as Float32Array, j * 16));
				checks.push(
					`            Check {\n                steps: ${steps},\n                pose: ${floats(pose, 10, inCheck)},\n                skin: ${floats(skin, 12, inCheck)},\n            },\n`,
				);
			},
		});
		out += `    Script {\n        name: "${script.name}",\n        step: ${float(SCRIPT_STEP)},\n        checks: &[\n${checks.join('')}        ],\n        loops: ${loops},\n        finished: ${finished},\n    },\n`;
	}
	return `${out}];\n`;
}

mkdirSync(FIXTURES, { recursive: true });
mkdirSync(CORE_FIXTURES, { recursive: true });
for (const [folder, file, text] of [
	[FIXTURES, 'three_mesh_arrays.rs', meshArraysFixture()],
	[FIXTURES, 'three_geometry.rs', geometryFixture()],
	[CORE_FIXTURES, 'three_animation.rs', animationFixture()],
] as const) {
	const path = join(folder, file);
	writeFileSync(path, text);
	// The modules sit in the Rust tests, which rustfmt checks.
	const formatted = Bun.spawnSync(['rustfmt', '--edition', '2024', path]);
	if (formatted.exitCode !== 0) throw new Error(`rustfmt failed: ${formatted.stderr.toString()}`);
	console.log(`wrote ${dirname(path)}/${file}`);
}
