// Writes the fixture that the engine core's tests of meshes from arrays compare with: the normals
// that three.js's computeVertexNormals gives and the tangents that its computeTangents gives, for a
// few small meshes, as the bits of their 32-bit floats, in a Rust module. From the repository root:
//   bun bench/three-fixtures.ts
// The meshes have shared vertices, triangles of many sizes, texture coordinates that mirror and
// that enclose no area, a triangle that repeats a vertex, and a vertex that no triangle uses.
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { BufferAttribute, BufferGeometry, REVISION } from 'three';

const OUT = join(
	import.meta.dirname,
	'../crates/null3d-render/tests/fixtures/three_mesh_arrays.rs',
);

interface Mesh {
	name: string;
	positions: Float32Array;
	uvs: Float32Array;
	indices: number[] | null;
}

/** An uneven grid of `columns` x `rows` quads with texture coordinates that mirror halfway. */
function indexedMesh(columns: number, rows: number): Mesh {
	const positions: number[] = [];
	const uvs: number[] = [];
	for (let j = 0; j <= rows; j++) {
		for (let i = 0; i <= columns; i++) {
			positions.push(
				i + 0.3 * Math.sin(i * 1.7 + j),
				j + 0.25 * Math.cos(i + j * 2.3),
				0.4 * Math.sin(i * 0.9) * Math.cos(j * 1.1),
			);
			const u = i / columns;
			uvs.push(i * 2 <= columns ? u : 1 - u, j / rows + 0.01 * Math.sin(i * 3.1));
		}
	}
	const row = columns + 1;
	const indices: number[] = [];
	for (let j = 0; j < rows; j++) {
		for (let i = 0; i < columns; i++) {
			const a = j * row + i;
			const b = (j + 1) * row + i;
			indices.push(a, a + 1, b, b, a + 1, b + 1);
		}
	}
	// A triangle that repeats a vertex, and one whose texture coordinates enclose no area.
	indices.push(0, 0, 1);
	uvs.push(0.5, 0.5, 0.5, 0.5, 0.5, 0.5);
	positions.push(0.1, 0.2, 0.3, 1.1, 0.4, -0.2, 0.3, 1.5, 0.7);
	const flat = positions.length / 3 - 3;
	indices.push(flat, flat + 1, flat + 2);
	// A vertex that no triangle uses.
	positions.push(9, 9, 9);
	uvs.push(0.25, 0.75);
	return {
		name: 'INDEXED',
		positions: new Float32Array(positions),
		uvs: new Float32Array(uvs),
		indices,
	};
}

/** Triangles without indices: three vertices each, one of them with a repeated position. */
function soup(): Mesh {
	const positions = [
		0, 0, 0, 1.3, 0.1, 0.2, 0.2, 1.1, -0.4, 2, 0.5, 1, 2.7, 1.9, 0.3, 1.1, 2.3, 0.8, 3, 3, 3, 3, 3,
		3, 4, 1, 0,
	];
	const uvs: number[] = [];
	for (let k = 0; k < positions.length; k += 3)
		uvs.push((positions[k] as number) / 4, (positions[k + 1] as number) / 4);
	return {
		name: 'SOUP',
		positions: new Float32Array(positions),
		uvs: new Float32Array(uvs),
		indices: null,
	};
}

/** The bits of 32-bit values, as a Rust array literal. */
function bits(values: Float32Array | Uint32Array): string {
	const words = new Uint32Array(values.buffer, values.byteOffset, values.length);
	const hex = Array.from(words, (w) => `0x${w.toString(16).padStart(8, '0')}`);
	const lines: string[] = [];
	for (let k = 0; k < hex.length; k += 6) lines.push(`    ${hex.slice(k, k + 6).join(', ')},`);
	return `[\n${lines.join('\n')}\n]`;
}

function constant(name: string, values: Float32Array | Uint32Array): string {
	return `pub const ${name}: [u32; ${values.length}] = ${bits(values)};\n`;
}

let out = `// Generated by \`bun bench/three-fixtures.ts\` with three.js r${REVISION}: the bits of each mesh's\n// 32-bit positions, texture coordinates and indices, and of the normals and tangents that three.js\n// computes for them. Do not edit; run the script again.\n#![allow(dead_code)]\n`;
for (const mesh of [indexedMesh(6, 4), soup()]) {
	const geometry = new BufferGeometry();
	geometry.setAttribute('position', new BufferAttribute(mesh.positions, 3));
	geometry.setAttribute('uv', new BufferAttribute(mesh.uvs, 2));
	if (mesh.indices) geometry.setIndex(mesh.indices);
	geometry.computeVertexNormals();
	const normals = geometry.getAttribute('normal').array as Float32Array;
	out += `\npub mod ${mesh.name.toLowerCase()} {\n`;
	out += constant('POSITIONS', mesh.positions);
	out += constant('UVS', mesh.uvs);
	out += constant('NORMALS', normals);
	if (mesh.indices) {
		// three.js computes tangents only for meshes with indices.
		geometry.computeTangents();
		out += constant('INDICES', new Uint32Array(mesh.indices));
		out += constant('TANGENTS', geometry.getAttribute('tangent').array as Float32Array);
	}
	out += '}\n';
}
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out);
// The module sits in the Rust tests, which rustfmt checks.
const formatted = Bun.spawnSync(['rustfmt', '--edition', '2024', OUT]);
if (formatted.exitCode !== 0) throw new Error(`rustfmt failed: ${formatted.stderr.toString()}`);
console.log(`wrote ${OUT}`);
