// Writes the fixtures that the engine core's tests compare with, as Rust modules, from the pinned
// three.js. From the repository root:
//   bun bench/three-fixtures.ts
// - three_mesh_arrays.rs: the normals that three.js's computeVertexNormals gives and the tangents
//   that its computeTangents gives for a few small meshes, as the bits of their 32-bit floats. The
//   meshes have shared vertices, triangles of many sizes, texture coordinates that mirror and that
//   enclose no area, a triangle that repeats a vertex, and a vertex that no triangle uses.
// - three_geometry.rs: the arrays that each geometry class builds, with its defaults and with
//   arguments that reach its special cases, as counts and digests of their bits.
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import {
	BoxGeometry,
	BufferAttribute,
	BufferGeometry,
	CapsuleGeometry,
	CircleGeometry,
	ConeGeometry,
	CylinderGeometry,
	PlaneGeometry,
	REVISION,
	RingGeometry,
	SphereGeometry,
	TorusGeometry,
} from 'three';

const FIXTURES = join(import.meta.dirname, '../crates/null3d-render/tests/fixtures');

interface Mesh {
	name: string;
	positions: Float32Array;
	uvs: Float32Array;
	indices: number[] | null;
}

/** An uneven grid of `columns` x `rows` quads with texture coordinates that mirror halfway. */
function indexedMesh(columns: number, rows: number): Mesh {
	const positions: number[] = [];
	const uvs: number[] = [];
	for (let j = 0; j <= rows; j++) {
		for (let i = 0; i <= columns; i++) {
			positions.push(
				i + 0.3 * Math.sin(i * 1.7 + j),
				j + 0.25 * Math.cos(i + j * 2.3),
				0.4 * Math.sin(i * 0.9) * Math.cos(j * 1.1),
			);
			const u = i / columns;
			uvs.push(i * 2 <= columns ? u : 1 - u, j / rows + 0.01 * Math.sin(i * 3.1));
		}
	}
	const row = columns + 1;
	const indices: number[] = [];
	for (let j = 0; j < rows; j++) {
		for (let i = 0; i < columns; i++) {
			const a = j * row + i;
			const b = (j + 1) * row + i;
			indices.push(a, a + 1, b, b, a + 1, b + 1);
		}
	}
	// A triangle that repeats a vertex, and one whose texture coordinates enclose no area.
	indices.push(0, 0, 1);
	uvs.push(0.5, 0.5, 0.5, 0.5, 0.5, 0.5);
	positions.push(0.1, 0.2, 0.3, 1.1, 0.4, -0.2, 0.3, 1.5, 0.7);
	const flat = positions.length / 3 - 3;
	indices.push(flat, flat + 1, flat + 2);
	// A vertex that no triangle uses.
	positions.push(9, 9, 9);
	uvs.push(0.25, 0.75);
	return {
		name: 'INDEXED',
		positions: new Float32Array(positions),
		uvs: new Float32Array(uvs),
		indices,
	};
}

/** Triangles without indices: three vertices each, one of them with a repeated position. */
function soup(): Mesh {
	const positions = [
		0, 0, 0, 1.3, 0.1, 0.2, 0.2, 1.1, -0.4, 2, 0.5, 1, 2.7, 1.9, 0.3, 1.1, 2.3, 0.8, 3, 3, 3, 3, 3,
		3, 4, 1, 0,
	];
	const uvs: number[] = [];
	for (let k = 0; k < positions.length; k += 3)
		uvs.push((positions[k] as number) / 4, (positions[k + 1] as number) / 4);
	return {
		name: 'SOUP',
		positions: new Float32Array(positions),
		uvs: new Float32Array(uvs),
		indices: null,
	};
}

/** The words of 32-bit values. */
function words(values: Float32Array | Uint32Array | Uint16Array): Uint32Array {
	return values instanceof Uint16Array
		? Uint32Array.from(values)
		: new Uint32Array(values.buffer, values.byteOffset, values.length);
}

/** The bits of 32-bit values, as a Rust array literal. */
function bits(values: Float32Array | Uint32Array): string {
	const hex = Array.from(words(values), (w) => `0x${w.toString(16).padStart(8, '0')}`);
	const lines: string[] = [];
	for (let k = 0; k < hex.length; k += 6) lines.push(`    ${hex.slice(k, k + 6).join(', ')},`);
	return `[\n${lines.join('\n')}\n]`;
}

function constant(name: string, values: Float32Array | Uint32Array): string {
	return `pub const ${name}: [u32; ${values.length}] = ${bits(values)};\n`;
}

function meshArraysFixture(): string {
	let out = `// Generated by \`bun bench/three-fixtures.ts\` with three.js r${REVISION}: the bits of each mesh's\n// 32-bit positions, texture coordinates and indices, and of the normals and tangents that three.js\n// computes for them. Do not edit; run the script again.\n#![allow(dead_code)]\n`;
	for (const mesh of [indexedMesh(6, 4), soup()]) {
		const geometry = new BufferGeometry();
		geometry.setAttribute('position', new BufferAttribute(mesh.positions, 3));
		geometry.setAttribute('uv', new BufferAttribute(mesh.uvs, 2));
		if (mesh.indices) geometry.setIndex(mesh.indices);
		geometry.computeVertexNormals();
		const normals = geometry.getAttribute('normal').array as Float32Array;
		out += `\npub mod ${mesh.name.toLowerCase()} {\n`;
		out += constant('POSITIONS', mesh.positions);
		out += constant('UVS', mesh.uvs);
		out += constant('NORMALS', normals);
		if (mesh.indices) {
			// three.js computes tangents only for meshes with indices.
			geometry.computeTangents();
			out += constant('INDICES', new Uint32Array(mesh.indices));
			out += constant('TANGENTS', geometry.getAttribute('tangent').array as Float32Array);
		}
		out += '}\n';
	}
	return out;
}

/** A three.js geometry, which keeps its constructor's arguments in `parameters`. */
type Generated = BufferGeometry & { parameters: Record<string, number | boolean> };
/** A geometry class of three.js. */
type GeometryClass = new (...args: never[]) => Generated;

/** Each class, and the engine's generator that builds its meshes. */
const GENERATORS = new Map<GeometryClass, string>([
	[BoxGeometry, 'box'],
	[SphereGeometry, 'sphere'],
	[PlaneGeometry, 'plane'],
	[CylinderGeometry, 'cylinder'],
	[ConeGeometry, 'cylinder'],
	[TorusGeometry, 'torus'],
	[CapsuleGeometry, 'capsule'],
	[CircleGeometry, 'circle'],
	[RingGeometry, 'ring'],
]);

/**
 * Each class with its defaults, then with arguments that reach its special cases: segment counts
 * that round down, partial arcs, open ends, points, poles away from the sphere's ends, and heights
 * of 0 and below.
 */
const GENERATOR_CASES: [GeometryClass, (number | boolean)[]][] = [
	[BoxGeometry, []],
	[BoxGeometry, [2, 0.5, 1.5, 3, 2, 4]],
	[BoxGeometry, [1, 1, 0]],
	[SphereGeometry, []],
	[SphereGeometry, [0.7, 7.6, 5, 0.3, 4, 0.4, 1.9]],
	[SphereGeometry, [2, 3, 2, 0, Math.PI * 2, 1, 3]],
	[PlaneGeometry, []],
	[PlaneGeometry, [3, 2, 4, 3]],
	[CylinderGeometry, []],
	[CylinderGeometry, [0.5, 1.2, 2, 7, 3, true, 0.3, 4.1]],
	[CylinderGeometry, [0.8, 0, 1.5, 5, 2]],
	[ConeGeometry, []],
	[ConeGeometry, [0.6, 2, 6, 3, false, 1, 3]],
	[TorusGeometry, []],
	[TorusGeometry, [2, 0.25, 5, 9, 3.5, 0.5, 4.2]],
	[CapsuleGeometry, []],
	[CapsuleGeometry, [0.5, 2, 3, 7, 4]],
	[CapsuleGeometry, [0.4, -1, 2, 5]],
	[CircleGeometry, []],
	[CircleGeometry, [2.5, 5, 0.5, 3]],
	[RingGeometry, []],
	[RingGeometry, [0.2, 1.4, 6, 3, 1, 4]],
];

/** FNV-1a over the little-endian bytes of 32-bit words, as a Rust literal. */
function digest(values: Float32Array | Uint32Array | Uint16Array): string {
	const w = words(values);
	let hash = 0xcbf29ce484222325n;
	for (const byte of new Uint8Array(w.buffer, w.byteOffset, w.byteLength))
		hash = ((hash ^ BigInt(byte)) * 0x100000001b3n) & 0xffffffffffffffffn;
	return `0x${hash.toString(16).padStart(16, '0')}`;
}

/** The bits of a 64-bit float, as a Rust literal. */
function float64(value: number): string {
	const view = new DataView(new ArrayBuffer(8));
	view.setFloat64(0, value);
	return `0x${view.getBigUint64(0).toString(16).padStart(16, '0')}`;
}

function geometryFixture(): string {
	let out = `// Generated by \`bun bench/three-fixtures.ts\` with three.js r${REVISION}: the arrays that each\n// geometry class builds, with its defaults and with other arguments. Do not edit; run the script\n// again.\n#![allow(dead_code)]\n\n`;
	out += `/// One mesh as a three.js geometry class builds it.
pub struct Case {
    /// The class and the arguments it was given.
    pub name: &'static str,
    /// The engine's generator that builds the same mesh.
    pub shape: &'static str,
    /// The bits of the constructor's arguments as 64-bit floats, in their order, with booleans as
    /// 1 or 0 and zeros after the last. A cone's are those of its cylinder, whose top radius is 0.
    pub args: [u64; 8],
    pub vertices: usize,
    pub indices: usize,
    /// FNV-1a digests of the bits of the 32-bit positions, normals, texture coordinates and
    /// indices.
    pub positions: u64,
    pub normals: u64,
    pub uvs: u64,
    pub triangles: u64,
}\n\n`;
	out += `pub const CASES: [Case; ${GENERATOR_CASES.length}] = [\n`;
	for (const [Class, given] of GENERATOR_CASES) {
		const make = Class as unknown as new (...args: (number | boolean)[]) => Generated;
		const geometry = new make(...given);
		const args = Object.values(geometry.parameters).map(Number);
		if (Class === ConeGeometry) args.unshift(0);
		while (args.length < 8) args.push(0);
		const attribute = (name: string) => geometry.getAttribute(name).array as Float32Array;
		const index = geometry.getIndex()?.array as Uint16Array | Uint32Array;
		out += `    Case {
        name: "new ${Class.name}(${given.join(', ')})",
        shape: "${GENERATORS.get(Class)}",
        args: [${args.map(float64).join(', ')}],
        vertices: ${geometry.getAttribute('position').count},
        indices: ${index.length},
        positions: ${digest(attribute('position'))},
        normals: ${digest(attribute('normal'))},
        uvs: ${digest(attribute('uv'))},
        triangles: ${digest(index)},
    },\n`;
	}
	return `${out}];\n`;
}

mkdirSync(FIXTURES, { recursive: true });
for (const [file, text] of [
	['three_mesh_arrays.rs', meshArraysFixture()],
	['three_geometry.rs', geometryFixture()],
] as const) {
	const path = join(FIXTURES, file);
	writeFileSync(path, text);
	// The modules sit in the Rust tests, which rustfmt checks.
	const formatted = Bun.spawnSync(['rustfmt', '--edition', '2024', path]);
	if (formatted.exitCode !== 0) throw new Error(`rustfmt failed: ${formatted.stderr.toString()}`);
	console.log(`wrote ${dirname(path)}/${file}`);
}
