//! Numbers TypeScript shares with the engine core, written out as a generated TypeScript module so
//! neither side copies them by hand.

use sokko3d_core::handle::{GENERATION_BITS, SLOT_BITS};
use sokko3d_core::scene::{NO_PARENT, flags, op};
use sokko3d_core::world::MATRIX_FLOATS;
use sokko3d_render::gpu_driven::{NO_MATERIAL, NO_MESH};

/// Fields of `sceneArrays`.
pub mod scene_field {
    pub const POSITIONS: u32 = 0;
    pub const ROTATIONS: u32 = 1;
    pub const SCALES: u32 = 2;
    pub const LOCAL_RADII: u32 = 3;
    pub const DIRTY_WORDS: u32 = 4;
}

/// Fields of `batchArrays`.
pub mod batch_field {
    pub const POSITIONS: u32 = 0;
    pub const ROTATIONS: u32 = 1;
    pub const SCALES: u32 = 2;
    pub const COLORS: u32 = 3;
}

/// Fields of `commandRing`.
pub mod ring_field {
    pub const RECORDS: u32 = 0;
    pub const CAPACITY: u32 = 1;
    pub const WRITE_INDEX: u32 = 2;
    pub const READ_INDEX: u32 = 3;
}

/// 32-bit words in one command record.
pub const COMMAND_WORDS: u32 = 4;

/// The generated module's text.
pub fn typescript() -> String {
    let mut out = String::from(
        "// Generated by `cargo test -p sokko3d-wasm` from crates/sokko3d-wasm/src/constants.rs.\n\
         // Do not edit: set SOKKO3D_UPDATE_GENERATED=1 and run that command to rewrite it.\n\n",
    );
    let groups: [(&str, &[(&str, u32)]); 7] = [
        (
            "COMMAND",
            &[
                ("CREATE", op::CREATE),
                ("DESTROY", op::DESTROY),
                ("SET_PARENT", op::SET_PARENT),
                ("SET_MESH", op::SET_MESH),
                ("SET_MATERIAL", op::SET_MATERIAL),
                ("SET_DYNAMIC", op::SET_DYNAMIC),
                ("SET_VISIBLE", op::SET_VISIBLE),
                ("WORDS", COMMAND_WORDS),
            ],
        ),
        (
            "FLAG",
            &[("DYNAMIC", flags::DYNAMIC), ("VISIBLE", flags::VISIBLE)],
        ),
        (
            "SCENE_FIELD",
            &[
                ("POSITIONS", scene_field::POSITIONS),
                ("ROTATIONS", scene_field::ROTATIONS),
                ("SCALES", scene_field::SCALES),
                ("LOCAL_RADII", scene_field::LOCAL_RADII),
                ("DIRTY_WORDS", scene_field::DIRTY_WORDS),
            ],
        ),
        (
            "BATCH_FIELD",
            &[
                ("POSITIONS", batch_field::POSITIONS),
                ("ROTATIONS", batch_field::ROTATIONS),
                ("SCALES", batch_field::SCALES),
                ("COLORS", batch_field::COLORS),
            ],
        ),
        (
            "RING_FIELD",
            &[
                ("RECORDS", ring_field::RECORDS),
                ("CAPACITY", ring_field::CAPACITY),
                ("WRITE_INDEX", ring_field::WRITE_INDEX),
                ("READ_INDEX", ring_field::READ_INDEX),
            ],
        ),
        (
            "HANDLE",
            &[
                ("SLOT_BITS", SLOT_BITS),
                ("GENERATION_BITS", GENERATION_BITS),
            ],
        ),
        (
            "CORE",
            &[
                ("NO_PARENT", NO_PARENT),
                ("NO_MESH", NO_MESH),
                ("NO_MATERIAL", NO_MATERIAL),
                ("MATRIX_FLOATS", MATRIX_FLOATS as u32),
            ],
        ),
    ];
    for (prefix, entries) in groups {
        for (name, value) in entries {
            out.push_str(&format!("export const {prefix}_{name} = {value};\n"));
        }
        out.push('\n');
    }
    out.pop();
    out
}

#[cfg(test)]
mod tests {
    #[test]
    fn the_generated_module_is_current() {
        let path = concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../packages/engine/src/generated/core.ts"
        );
        let expected = super::typescript();
        if std::env::var_os("SOKKO3D_UPDATE_GENERATED").is_some() {
            std::fs::write(path, &expected).unwrap();
        }
        let actual = std::fs::read_to_string(path).unwrap_or_default();
        assert!(
            actual == expected,
            "{path} is out of date: run `SOKKO3D_UPDATE_GENERATED=1 cargo test -p sokko3d-wasm`"
        );
    }
}
