// The keys the engine reads, by their KeyboardEvent.code names: the physical keys of the standard
// keyboard sections. A key's number in the input ring is its place in this list, so the page and the
// sketch number keys the same way. A key outside the list never reaches the sketch.

const numbered = (prefix: string, from: number, to: number): string[] =>
	Array.from({ length: to - from + 1 }, (_, k) => `${prefix}${from + k}`);

/** KeyboardEvent.code names, in the order of their numbers. */
export const KEY_CODES: readonly string[] = [
	...Array.from('ABCDEFGHIJKLMNOPQRSTUVWXYZ', (letter) => `Key${letter}`),
	...numbered('Digit', 0, 9),
	...numbered('F', 1, 24),
	...numbered('Numpad', 0, 9),
	'Backquote',
	'Minus',
	'Equal',
	'BracketLeft',
	'BracketRight',
	'Backslash',
	'Semicolon',
	'Quote',
	'Comma',
	'Period',
	'Slash',
	'IntlBackslash',
	'IntlRo',
	'IntlYen',
	'Space',
	'Enter',
	'Tab',
	'Backspace',
	'Escape',
	'CapsLock',
	'ShiftLeft',
	'ShiftRight',
	'ControlLeft',
	'ControlRight',
	'AltLeft',
	'AltRight',
	'MetaLeft',
	'MetaRight',
	'ContextMenu',
	'Fn',
	'ArrowUp',
	'ArrowDown',
	'ArrowLeft',
	'ArrowRight',
	'Insert',
	'Delete',
	'Home',
	'End',
	'PageUp',
	'PageDown',
	'Help',
	'PrintScreen',
	'ScrollLock',
	'Pause',
	'NumLock',
	'NumpadAdd',
	'NumpadSubtract',
	'NumpadMultiply',
	'NumpadDivide',
	'NumpadDecimal',
	'NumpadComma',
	'NumpadEnter',
	'NumpadEqual',
	'Convert',
	'NonConvert',
	'KanaMode',
	'Lang1',
	'Lang2',
];
